/*
* generated by Xtext
*/
package cruise.umple.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import cruise.umple.services.UmpleGrammarAccess;

public class UmpleParser extends AbstractContentAssistParser {
	
	@Inject
	private UmpleGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected cruise.umple.ui.contentassist.antlr.internal.InternalUmpleParser createParser() {
		cruise.umple.ui.contentassist.antlr.internal.InternalUmpleParser result = new cruise.umple.ui.contentassist.antlr.internal.InternalUmpleParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getUmpleModelAccess().getAlternatives_4(), "rule__UmpleModel__Alternatives_4");
					put(grammarAccess.getUmpleElementAccess().getAlternatives(), "rule__UmpleElement__Alternatives");
					put(grammarAccess.getGenerateAccess().getAlternatives_1(), "rule__Generate__Alternatives_1");
					put(grammarAccess.getUmpleClassAccess().getAlternatives_10(), "rule__UmpleClass__Alternatives_10");
					put(grammarAccess.getExternalLanguageAccess().getAlternatives(), "rule__ExternalLanguage__Alternatives");
					put(grammarAccess.getPrimitiveTypeAccess().getAlternatives(), "rule__PrimitiveType__Alternatives");
					put(grammarAccess.getAssociationClassContentAccess().getAlternatives(), "rule__AssociationClassContent__Alternatives");
					put(grammarAccess.getAssociationAccess().getAlternatives_3(), "rule__Association__Alternatives_3");
					put(grammarAccess.getInlineAssociationAccess().getAlternatives_2(), "rule__InlineAssociation__Alternatives_2");
					put(grammarAccess.getMultiplicityAccess().getAlternatives(), "rule__Multiplicity__Alternatives");
					put(grammarAccess.getBoundAccess().getAlternatives(), "rule__Bound__Alternatives");
					put(grammarAccess.getCodeInjectionAccess().getAlternatives(), "rule__CodeInjection__Alternatives");
					put(grammarAccess.getUmpleAttributeAccess().getAlternatives(), "rule__UmpleAttribute__Alternatives");
					put(grammarAccess.getUmpleAttributeAccess().getAlternatives_1_2(), "rule__UmpleAttribute__Alternatives_1_2");
					put(grammarAccess.getUmplePrimitiveTypeAccess().getAlternatives(), "rule__UmplePrimitiveType__Alternatives");
					put(grammarAccess.getUmpleAttributeTypeAccess().getAlternatives(), "rule__UmpleAttributeType__Alternatives");
					put(grammarAccess.getStateMachineAccess().getAlternatives(), "rule__StateMachine__Alternatives");
					put(grammarAccess.getStateAccess().getAlternatives(), "rule__State__Alternatives");
					put(grammarAccess.getStateEntityAccess().getAlternatives(), "rule__StateEntity__Alternatives");
					put(grammarAccess.getTransitionAccess().getAlternatives(), "rule__Transition__Alternatives");
					put(grammarAccess.getEventDefinitionAccess().getAlternatives(), "rule__EventDefinition__Alternatives");
					put(grammarAccess.getTimedEventAccess().getAlternatives_2(), "rule__TimedEvent__Alternatives_2");
					put(grammarAccess.getWaitEventAccess().getAlternatives_2(), "rule__WaitEvent__Alternatives_2");
					put(grammarAccess.getEntryOrExitActionAccess().getAlternatives_0(), "rule__EntryOrExitAction__Alternatives_0");
					put(grammarAccess.getPositionAccess().getAlternatives(), "rule__Position__Alternatives");
					put(grammarAccess.getTraceDirectiveAccess().getTraceStartAlternatives_0_0(), "rule__TraceDirective__TraceStartAlternatives_0_0");
					put(grammarAccess.getTraceConditionAccess().getAlternatives(), "rule__TraceCondition__Alternatives");
					put(grammarAccess.getModelElementAccess().getAlternatives(), "rule__ModelElement__Alternatives");
					put(grammarAccess.getModelElementAccess().getAlternatives_0_0(), "rule__ModelElement__Alternatives_0_0");
					put(grammarAccess.getComparisonOperatorAccess().getAlternatives(), "rule__ComparisonOperator__Alternatives");
					put(grammarAccess.getAssignmentOperatorAccess().getAlternatives(), "rule__AssignmentOperator__Alternatives");
					put(grammarAccess.getEqualityExpressionAccess().getAlternatives_1_0(), "rule__EqualityExpression__Alternatives_1_0");
					put(grammarAccess.getRelationalOpAccess().getAlternatives(), "rule__RelationalOp__Alternatives");
					put(grammarAccess.getAdditiveExpressionAccess().getAlternatives_1_0(), "rule__AdditiveExpression__Alternatives_1_0");
					put(grammarAccess.getMultiplicativeExpressionAccess().getAlternatives_1_0(), "rule__MultiplicativeExpression__Alternatives_1_0");
					put(grammarAccess.getUnaryExpressionAccess().getAlternatives(), "rule__UnaryExpression__Alternatives");
					put(grammarAccess.getUnaryExpressionNotPlusMinusAccess().getAlternatives(), "rule__UnaryExpressionNotPlusMinus__Alternatives");
					put(grammarAccess.getUnaryExpressionNotPlusMinusAccess().getAlternatives_2_1(), "rule__UnaryExpressionNotPlusMinus__Alternatives_2_1");
					put(grammarAccess.getPrimaryAccess().getAlternatives(), "rule__Primary__Alternatives");
					put(grammarAccess.getLiteralAccess().getAlternatives(), "rule__Literal__Alternatives");
					put(grammarAccess.getJavaFunctionDeclarationAccess().getAlternatives_1(), "rule__JavaFunctionDeclaration__Alternatives_1");
					put(grammarAccess.getJavaFunctionDeclarationAccess().getAlternatives_2(), "rule__JavaFunctionDeclaration__Alternatives_2");
					put(grammarAccess.getJavaFunctionDeclarationAccess().getAlternatives_4(), "rule__JavaFunctionDeclaration__Alternatives_4");
					put(grammarAccess.getJavaFunctionCallAccess().getAlternatives_1(), "rule__JavaFunctionCall__Alternatives_1");
					put(grammarAccess.getBlockStatementAccess().getAlternatives(), "rule__BlockStatement__Alternatives");
					put(grammarAccess.getStatementAccess().getAlternatives(), "rule__Statement__Alternatives");
					put(grammarAccess.getForInitAccess().getAlternatives(), "rule__ForInit__Alternatives");
					put(grammarAccess.getAttributeTypeAccess().getAlternatives(), "rule__AttributeType__Alternatives");
					put(grammarAccess.getCHARSAccess().getAlternatives(), "rule__CHARS__Alternatives");
					put(grammarAccess.getModifierAccess().getAlternatives(), "rule__Modifier__Alternatives");
					put(grammarAccess.getUmpleModelAccess().getGroup(), "rule__UmpleModel__Group__0");
					put(grammarAccess.getWordAccess().getGroup(), "rule__Word__Group__0");
					put(grammarAccess.getGlossaryAccess().getGroup(), "rule__Glossary__Group__0");
					put(grammarAccess.getGenerateAccess().getGroup(), "rule__Generate__Group__0");
					put(grammarAccess.getUseStatementAccess().getGroup(), "rule__UseStatement__Group__0");
					put(grammarAccess.getNamespaceAccess().getGroup(), "rule__Namespace__Group__0");
					put(grammarAccess.getUmpleClassAccess().getGroup(), "rule__UmpleClass__Group__0");
					put(grammarAccess.getUmpleClassAccess().getGroup_9(), "rule__UmpleClass__Group_9__0");
					put(grammarAccess.getUmpleClassAccess().getGroup_9_2(), "rule__UmpleClass__Group_9_2__0");
					put(grammarAccess.getUmpleInterfaceAccess().getGroup(), "rule__UmpleInterface__Group__0");
					put(grammarAccess.getUmpleInterfaceAccess().getGroup_4(), "rule__UmpleInterface__Group_4__0");
					put(grammarAccess.getUmpleAssociationAccess().getGroup(), "rule__UmpleAssociation__Group__0");
					put(grammarAccess.getUmpleAssociationClassAccess().getGroup(), "rule__UmpleAssociationClass__Group__0");
					put(grammarAccess.getAssociationAccess().getGroup(), "rule__Association__Group__0");
					put(grammarAccess.getSymmetricReflexiveAssociationAccess().getGroup(), "rule__SymmetricReflexiveAssociation__Group__0");
					put(grammarAccess.getInlineAssociationAccess().getGroup(), "rule__InlineAssociation__Group__0");
					put(grammarAccess.getSingleAssociationEndAccess().getGroup(), "rule__SingleAssociationEnd__Group__0");
					put(grammarAccess.getMultiplicityAccess().getGroup_1(), "rule__Multiplicity__Group_1__0");
					put(grammarAccess.getSingletonAccess().getGroup(), "rule__Singleton__Group__0");
					put(grammarAccess.getCodeInjectionAccess().getGroup_0(), "rule__CodeInjection__Group_0__0");
					put(grammarAccess.getCodeInjectionAccess().getGroup_1(), "rule__CodeInjection__Group_1__0");
					put(grammarAccess.getUmpleAttributeAccess().getGroup_0(), "rule__UmpleAttribute__Group_0__0");
					put(grammarAccess.getUmpleAttributeAccess().getGroup_1(), "rule__UmpleAttribute__Group_1__0");
					put(grammarAccess.getUmpleAttributeAccess().getGroup_1_2_0(), "rule__UmpleAttribute__Group_1_2_0__0");
					put(grammarAccess.getUmpleAttributeAccess().getGroup_1_2_1(), "rule__UmpleAttribute__Group_1_2_1__0");
					put(grammarAccess.getUmpleAttributeAccess().getGroup_1_4(), "rule__UmpleAttribute__Group_1_4__0");
					put(grammarAccess.getKeyAccess().getGroup(), "rule__Key__Group__0");
					put(grammarAccess.getKeyAccess().getGroup_3(), "rule__Key__Group_3__0");
					put(grammarAccess.getKeyAccess().getGroup_3_1(), "rule__Key__Group_3_1__0");
					put(grammarAccess.getDependAccess().getGroup(), "rule__Depend__Group__0");
					put(grammarAccess.getStateMachineDefinitionAccess().getGroup(), "rule__StateMachineDefinition__Group__0");
					put(grammarAccess.getInlineStateMachineAccess().getGroup(), "rule__InlineStateMachine__Group__0");
					put(grammarAccess.getReferencedStateMachineAccess().getGroup(), "rule__ReferencedStateMachine__Group__0");
					put(grammarAccess.getENUMAccess().getGroup(), "rule__ENUM__Group__0");
					put(grammarAccess.getENUMAccess().getGroup_3(), "rule__ENUM__Group_3__0");
					put(grammarAccess.getStateAccess().getGroup_1(), "rule__State__Group_1__0");
					put(grammarAccess.getStateAccess().getGroup_1_5(), "rule__State__Group_1_5__0");
					put(grammarAccess.getStateEntityAccess().getGroup_2(), "rule__StateEntity__Group_2__0");
					put(grammarAccess.getStateEntityAccess().getGroup_2_1(), "rule__StateEntity__Group_2_1__0");
					put(grammarAccess.getStateEntityAccess().getGroup_4(), "rule__StateEntity__Group_4__0");
					put(grammarAccess.getTransitionAccess().getGroup_0(), "rule__Transition__Group_0__0");
					put(grammarAccess.getTransitionAccess().getGroup_1(), "rule__Transition__Group_1__0");
					put(grammarAccess.getEventDefinitionAccess().getGroup_0(), "rule__EventDefinition__Group_0__0");
					put(grammarAccess.getEventDefinitionAccess().getGroup_1(), "rule__EventDefinition__Group_1__0");
					put(grammarAccess.getTimedEventAccess().getGroup(), "rule__TimedEvent__Group__0");
					put(grammarAccess.getWaitEventAccess().getGroup(), "rule__WaitEvent__Group__0");
					put(grammarAccess.getActionAccess().getGroup(), "rule__Action__Group__0");
					put(grammarAccess.getEntryOrExitActionAccess().getGroup(), "rule__EntryOrExitAction__Group__0");
					put(grammarAccess.getActivityAccess().getGroup(), "rule__Activity__Group__0");
					put(grammarAccess.getGuardAccess().getGroup(), "rule__Guard__Group__0");
					put(grammarAccess.getClassPositionAccess().getGroup(), "rule__ClassPosition__Group__0");
					put(grammarAccess.getAssociationPositionAccess().getGroup(), "rule__AssociationPosition__Group__0");
					put(grammarAccess.getCoordinateAccess().getGroup(), "rule__Coordinate__Group__0");
					put(grammarAccess.getTraceDirectiveAccess().getGroup(), "rule__TraceDirective__Group__0");
					put(grammarAccess.getTraceCaseAccess().getGroup(), "rule__TraceCase__Group__0");
					put(grammarAccess.getTraceRecordAccess().getGroup(), "rule__TraceRecord__Group__0");
					put(grammarAccess.getTraceRecordAccess().getGroup_0(), "rule__TraceRecord__Group_0__0");
					put(grammarAccess.getTraceRecordAccess().getGroup_0_3(), "rule__TraceRecord__Group_0_3__0");
					put(grammarAccess.getSimpleTraceConditionAccess().getGroup(), "rule__SimpleTraceCondition__Group__0");
					put(grammarAccess.getConditionRHSAccess().getGroup(), "rule__ConditionRHS__Group__0");
					put(grammarAccess.getModelElementAccess().getGroup_0(), "rule__ModelElement__Group_0__0");
					put(grammarAccess.getTraceMechanismAccess().getGroup(), "rule__TraceMechanism__Group__0");
					put(grammarAccess.getBlockAccess().getGroup(), "rule__Block__Group__0");
					put(grammarAccess.getParExpressionAccess().getGroup(), "rule__ParExpression__Group__0");
					put(grammarAccess.getExpressionListAccess().getGroup(), "rule__ExpressionList__Group__0");
					put(grammarAccess.getExpressionListAccess().getGroup_1(), "rule__ExpressionList__Group_1__0");
					put(grammarAccess.getExpressionAccess().getGroup(), "rule__Expression__Group__0");
					put(grammarAccess.getExpressionAccess().getGroup_1(), "rule__Expression__Group_1__0");
					put(grammarAccess.getConditionalExpressionAccess().getGroup(), "rule__ConditionalExpression__Group__0");
					put(grammarAccess.getConditionalExpressionAccess().getGroup_1(), "rule__ConditionalExpression__Group_1__0");
					put(grammarAccess.getConditionalOrExpressionAccess().getGroup(), "rule__ConditionalOrExpression__Group__0");
					put(grammarAccess.getConditionalOrExpressionAccess().getGroup_1(), "rule__ConditionalOrExpression__Group_1__0");
					put(grammarAccess.getConditionalAndExpressionAccess().getGroup(), "rule__ConditionalAndExpression__Group__0");
					put(grammarAccess.getConditionalAndExpressionAccess().getGroup_1(), "rule__ConditionalAndExpression__Group_1__0");
					put(grammarAccess.getEqualityExpressionAccess().getGroup(), "rule__EqualityExpression__Group__0");
					put(grammarAccess.getEqualityExpressionAccess().getGroup_1(), "rule__EqualityExpression__Group_1__0");
					put(grammarAccess.getRelationalExpressionAccess().getGroup(), "rule__RelationalExpression__Group__0");
					put(grammarAccess.getRelationalExpressionAccess().getGroup_1(), "rule__RelationalExpression__Group_1__0");
					put(grammarAccess.getAdditiveExpressionAccess().getGroup(), "rule__AdditiveExpression__Group__0");
					put(grammarAccess.getAdditiveExpressionAccess().getGroup_1(), "rule__AdditiveExpression__Group_1__0");
					put(grammarAccess.getMultiplicativeExpressionAccess().getGroup(), "rule__MultiplicativeExpression__Group__0");
					put(grammarAccess.getMultiplicativeExpressionAccess().getGroup_1(), "rule__MultiplicativeExpression__Group_1__0");
					put(grammarAccess.getUnaryExpressionAccess().getGroup_0(), "rule__UnaryExpression__Group_0__0");
					put(grammarAccess.getUnaryExpressionAccess().getGroup_1(), "rule__UnaryExpression__Group_1__0");
					put(grammarAccess.getUnaryExpressionAccess().getGroup_2(), "rule__UnaryExpression__Group_2__0");
					put(grammarAccess.getUnaryExpressionAccess().getGroup_3(), "rule__UnaryExpression__Group_3__0");
					put(grammarAccess.getUnaryExpressionNotPlusMinusAccess().getGroup_0(), "rule__UnaryExpressionNotPlusMinus__Group_0__0");
					put(grammarAccess.getUnaryExpressionNotPlusMinusAccess().getGroup_1(), "rule__UnaryExpressionNotPlusMinus__Group_1__0");
					put(grammarAccess.getUnaryExpressionNotPlusMinusAccess().getGroup_2(), "rule__UnaryExpressionNotPlusMinus__Group_2__0");
					put(grammarAccess.getJavaFunctionDeclarationAccess().getGroup(), "rule__JavaFunctionDeclaration__Group__0");
					put(grammarAccess.getJavaFunctionDeclarationAccess().getGroup_4_0(), "rule__JavaFunctionDeclaration__Group_4_0__0");
					put(grammarAccess.getJavaFunctionDeclarationAccess().getGroup_4_0_1(), "rule__JavaFunctionDeclaration__Group_4_0_1__0");
					put(grammarAccess.getJavaFunctionDeclarationAccess().getGroup_4_0_1_2(), "rule__JavaFunctionDeclaration__Group_4_0_1_2__0");
					put(grammarAccess.getJavaFunctionDefinitionAccess().getGroup(), "rule__JavaFunctionDefinition__Group__0");
					put(grammarAccess.getJavaFunctionCallAccess().getGroup(), "rule__JavaFunctionCall__Group__0");
					put(grammarAccess.getJavaFunctionCallAccess().getGroup_1_0(), "rule__JavaFunctionCall__Group_1_0__0");
					put(grammarAccess.getLocalVariableDeclarationStatementAccess().getGroup(), "rule__LocalVariableDeclarationStatement__Group__0");
					put(grammarAccess.getLocalVariableDeclarationAccess().getGroup(), "rule__LocalVariableDeclaration__Group__0");
					put(grammarAccess.getVariableDeclaratorsAccess().getGroup(), "rule__VariableDeclarators__Group__0");
					put(grammarAccess.getVariableDeclaratorsAccess().getGroup_1(), "rule__VariableDeclarators__Group_1__0");
					put(grammarAccess.getVariableDeclaratorAccess().getGroup(), "rule__VariableDeclarator__Group__0");
					put(grammarAccess.getVariableDeclaratorAccess().getGroup_1(), "rule__VariableDeclarator__Group_1__0");
					put(grammarAccess.getStatementAccess().getGroup_1(), "rule__Statement__Group_1__0");
					put(grammarAccess.getStatementAccess().getGroup_1_3(), "rule__Statement__Group_1_3__0");
					put(grammarAccess.getStatementAccess().getGroup_2(), "rule__Statement__Group_2__0");
					put(grammarAccess.getStatementAccess().getGroup_3(), "rule__Statement__Group_3__0");
					put(grammarAccess.getStatementAccess().getGroup_4(), "rule__Statement__Group_4__0");
					put(grammarAccess.getStatementAccess().getGroup_6(), "rule__Statement__Group_6__0");
					put(grammarAccess.getStatementAccess().getGroup_7(), "rule__Statement__Group_7__0");
					put(grammarAccess.getStatementAccess().getGroup_8(), "rule__Statement__Group_8__0");
					put(grammarAccess.getForControlAccess().getGroup(), "rule__ForControl__Group__0");
					put(grammarAccess.getForInitAccess().getGroup_0(), "rule__ForInit__Group_0__0");
					put(grammarAccess.getForInitAccess().getGroup_0_1(), "rule__ForInit__Group_0_1__0");
					put(grammarAccess.getPhpFunctionAccess().getGroup(), "rule__PhpFunction__Group__0");
					put(grammarAccess.getPhpBlockAccess().getGroup(), "rule__PhpBlock__Group__0");
					put(grammarAccess.getExtendedIDAccess().getGroup(), "rule__ExtendedID__Group__0");
					put(grammarAccess.getExtendedIDAccess().getGroup_1(), "rule__ExtendedID__Group_1__0");
					put(grammarAccess.getDOUBLEAccess().getGroup(), "rule__DOUBLE__Group__0");
					put(grammarAccess.getFileIDAccess().getGroup(), "rule__FileID__Group__0");
					put(grammarAccess.getUmpleModelAccess().getNamespaceAssignment_0(), "rule__UmpleModel__NamespaceAssignment_0");
					put(grammarAccess.getUmpleModelAccess().getGlossaryAssignment_1(), "rule__UmpleModel__GlossaryAssignment_1");
					put(grammarAccess.getUmpleModelAccess().getGenerate_Assignment_2(), "rule__UmpleModel__Generate_Assignment_2");
					put(grammarAccess.getUmpleModelAccess().getTraceMechanismAssignment_3(), "rule__UmpleModel__TraceMechanismAssignment_3");
					put(grammarAccess.getUmpleModelAccess().getUsesAssignment_4_0(), "rule__UmpleModel__UsesAssignment_4_0");
					put(grammarAccess.getUmpleModelAccess().getUmpleElementsAssignment_4_1(), "rule__UmpleModel__UmpleElementsAssignment_4_1");
					put(grammarAccess.getUmpleModelAccess().getAssociationsAssignment_4_2(), "rule__UmpleModel__AssociationsAssignment_4_2");
					put(grammarAccess.getUmpleModelAccess().getAssociationClassesAssignment_4_3(), "rule__UmpleModel__AssociationClassesAssignment_4_3");
					put(grammarAccess.getUmpleModelAccess().getStatemachinesAssignment_4_4(), "rule__UmpleModel__StatemachinesAssignment_4_4");
					put(grammarAccess.getWordAccess().getSingularAssignment_0(), "rule__Word__SingularAssignment_0");
					put(grammarAccess.getWordAccess().getPluralAssignment_2(), "rule__Word__PluralAssignment_2");
					put(grammarAccess.getGlossaryAccess().getWordsAssignment_3(), "rule__Glossary__WordsAssignment_3");
					put(grammarAccess.getGenerateAccess().getJavaAssignment_1_0(), "rule__Generate__JavaAssignment_1_0");
					put(grammarAccess.getGenerateAccess().getPhpAssignment_1_1(), "rule__Generate__PhpAssignment_1_1");
					put(grammarAccess.getGenerateAccess().getRubyAssignment_1_2(), "rule__Generate__RubyAssignment_1_2");
					put(grammarAccess.getNamespaceAccess().getValueAssignment_1(), "rule__Namespace__ValueAssignment_1");
					put(grammarAccess.getUmpleClassAccess().getPackageNameAssignment_1(), "rule__UmpleClass__PackageNameAssignment_1");
					put(grammarAccess.getUmpleClassAccess().getExternalAssignment_2(), "rule__UmpleClass__ExternalAssignment_2");
					put(grammarAccess.getUmpleClassAccess().getNameAssignment_4(), "rule__UmpleClass__NameAssignment_4");
					put(grammarAccess.getUmpleClassAccess().getSingletonAssignment_6(), "rule__UmpleClass__SingletonAssignment_6");
					put(grammarAccess.getUmpleClassAccess().getKeyAssignment_7(), "rule__UmpleClass__KeyAssignment_7");
					put(grammarAccess.getUmpleClassAccess().getCodeInjectionAssignment_8(), "rule__UmpleClass__CodeInjectionAssignment_8");
					put(grammarAccess.getUmpleClassAccess().getExtendsClassAssignment_9_1(), "rule__UmpleClass__ExtendsClassAssignment_9_1");
					put(grammarAccess.getUmpleClassAccess().getExtendsClassAssignment_9_2_1(), "rule__UmpleClass__ExtendsClassAssignment_9_2_1");
					put(grammarAccess.getUmpleClassAccess().getAttributesAssignment_10_0(), "rule__UmpleClass__AttributesAssignment_10_0");
					put(grammarAccess.getUmpleClassAccess().getSymmetricReflexiveAssociationsAssignment_10_1(), "rule__UmpleClass__SymmetricReflexiveAssociationsAssignment_10_1");
					put(grammarAccess.getUmpleClassAccess().getInlineAssociationsAssignment_10_2(), "rule__UmpleClass__InlineAssociationsAssignment_10_2");
					put(grammarAccess.getUmpleClassAccess().getDependsAssignment_10_3(), "rule__UmpleClass__DependsAssignment_10_3");
					put(grammarAccess.getUmpleClassAccess().getPositionsAssignment_10_4(), "rule__UmpleClass__PositionsAssignment_10_4");
					put(grammarAccess.getUmpleClassAccess().getStateMachinesAssignment_10_5(), "rule__UmpleClass__StateMachinesAssignment_10_5");
					put(grammarAccess.getUmpleClassAccess().getTraceDirectivesAssignment_10_6(), "rule__UmpleClass__TraceDirectivesAssignment_10_6");
					put(grammarAccess.getUmpleClassAccess().getTraceCasesAssignment_10_7(), "rule__UmpleClass__TraceCasesAssignment_10_7");
					put(grammarAccess.getUmpleClassAccess().getExternalLanguageAssignment_11(), "rule__UmpleClass__ExternalLanguageAssignment_11");
					put(grammarAccess.getExternalLanguageAccess().getFunctionsAssignment_0(), "rule__ExternalLanguage__FunctionsAssignment_0");
					put(grammarAccess.getExternalLanguageAccess().getRubyFunctionsAssignment_1(), "rule__ExternalLanguage__RubyFunctionsAssignment_1");
					put(grammarAccess.getExternalLanguageAccess().getPhpFunctionsAssignment_2(), "rule__ExternalLanguage__PhpFunctionsAssignment_2");
					put(grammarAccess.getUmpleInterfaceAccess().getNameAssignment_1(), "rule__UmpleInterface__NameAssignment_1");
					put(grammarAccess.getUmpleInterfaceAccess().getDependsAssignment_3(), "rule__UmpleInterface__DependsAssignment_3");
					put(grammarAccess.getUmpleInterfaceAccess().getExtraCodeAssignment_4_0(), "rule__UmpleInterface__ExtraCodeAssignment_4_0");
					put(grammarAccess.getUmpleAssociationAccess().getNameAssignment_1(), "rule__UmpleAssociation__NameAssignment_1");
					put(grammarAccess.getUmpleAssociationAccess().getAssociationsAssignment_3(), "rule__UmpleAssociation__AssociationsAssignment_3");
					put(grammarAccess.getUmpleAssociationClassAccess().getNameAssignment_1(), "rule__UmpleAssociationClass__NameAssignment_1");
					put(grammarAccess.getUmpleAssociationClassAccess().getAssociationClassContentsAssignment_3(), "rule__UmpleAssociationClass__AssociationClassContentsAssignment_3");
					put(grammarAccess.getAssociationAccess().getType1Assignment_1(), "rule__Association__Type1Assignment_1");
					put(grammarAccess.getAssociationAccess().getRolename1Assignment_2(), "rule__Association__Rolename1Assignment_2");
					put(grammarAccess.getAssociationAccess().getType2Assignment_5(), "rule__Association__Type2Assignment_5");
					put(grammarAccess.getAssociationAccess().getRolename2Assignment_6(), "rule__Association__Rolename2Assignment_6");
					put(grammarAccess.getSymmetricReflexiveAssociationAccess().getRolenameAssignment_2(), "rule__SymmetricReflexiveAssociation__RolenameAssignment_2");
					put(grammarAccess.getInlineAssociationAccess().getRolename1Assignment_1(), "rule__InlineAssociation__Rolename1Assignment_1");
					put(grammarAccess.getInlineAssociationAccess().getTypeAssignment_4(), "rule__InlineAssociation__TypeAssignment_4");
					put(grammarAccess.getInlineAssociationAccess().getRolename2Assignment_5(), "rule__InlineAssociation__Rolename2Assignment_5");
					put(grammarAccess.getSingleAssociationEndAccess().getTypeAssignment_1(), "rule__SingleAssociationEnd__TypeAssignment_1");
					put(grammarAccess.getSingleAssociationEndAccess().getRolenameAssignment_2(), "rule__SingleAssociationEnd__RolenameAssignment_2");
					put(grammarAccess.getSingletonAccess().getSingletonAssignment_0(), "rule__Singleton__SingletonAssignment_0");
					put(grammarAccess.getCodeInjectionAccess().getNameAssignment_0_1(), "rule__CodeInjection__NameAssignment_0_1");
					put(grammarAccess.getCodeInjectionAccess().getCodeAssignment_0_2(), "rule__CodeInjection__CodeAssignment_0_2");
					put(grammarAccess.getCodeInjectionAccess().getNameAssignment_1_1(), "rule__CodeInjection__NameAssignment_1_1");
					put(grammarAccess.getCodeInjectionAccess().getCodeAssignment_1_2(), "rule__CodeInjection__CodeAssignment_1_2");
					put(grammarAccess.getUmpleAttributeAccess().getAutouniqueAssignment_0_0(), "rule__UmpleAttribute__AutouniqueAssignment_0_0");
					put(grammarAccess.getUmpleAttributeAccess().getNameAssignment_0_1(), "rule__UmpleAttribute__NameAssignment_0_1");
					put(grammarAccess.getUmpleAttributeAccess().getUniqueAssignment_1_0(), "rule__UmpleAttribute__UniqueAssignment_1_0");
					put(grammarAccess.getUmpleAttributeAccess().getModifierAssignment_1_1(), "rule__UmpleAttribute__ModifierAssignment_1_1");
					put(grammarAccess.getUmpleAttributeAccess().getTypeAssignment_1_2_0_0(), "rule__UmpleAttribute__TypeAssignment_1_2_0_0");
					put(grammarAccess.getUmpleAttributeAccess().getListAssignment_1_2_0_1(), "rule__UmpleAttribute__ListAssignment_1_2_0_1");
					put(grammarAccess.getUmpleAttributeAccess().getObjectAssignment_1_2_1_0(), "rule__UmpleAttribute__ObjectAssignment_1_2_1_0");
					put(grammarAccess.getUmpleAttributeAccess().getListAssignment_1_2_1_1(), "rule__UmpleAttribute__ListAssignment_1_2_1_1");
					put(grammarAccess.getUmpleAttributeAccess().getNameAssignment_1_3(), "rule__UmpleAttribute__NameAssignment_1_3");
					put(grammarAccess.getUmpleAttributeAccess().getValueAssignment_1_4_1(), "rule__UmpleAttribute__ValueAssignment_1_4_1");
					put(grammarAccess.getKeyAccess().getKeysAssignment_3_0(), "rule__Key__KeysAssignment_3_0");
					put(grammarAccess.getKeyAccess().getKeysAssignment_3_1_1(), "rule__Key__KeysAssignment_3_1_1");
					put(grammarAccess.getDependAccess().getNameAssignment_1(), "rule__Depend__NameAssignment_1");
					put(grammarAccess.getStateMachineDefinitionAccess().getNameAssignment_1(), "rule__StateMachineDefinition__NameAssignment_1");
					put(grammarAccess.getStateMachineDefinitionAccess().getStatesAssignment_3(), "rule__StateMachineDefinition__StatesAssignment_3");
					put(grammarAccess.getInlineStateMachineAccess().getNameAssignment_0(), "rule__InlineStateMachine__NameAssignment_0");
					put(grammarAccess.getInlineStateMachineAccess().getStatesAssignment_2(), "rule__InlineStateMachine__StatesAssignment_2");
					put(grammarAccess.getReferencedStateMachineAccess().getNameAssignment_0(), "rule__ReferencedStateMachine__NameAssignment_0");
					put(grammarAccess.getReferencedStateMachineAccess().getMachineAssignment_2(), "rule__ReferencedStateMachine__MachineAssignment_2");
					put(grammarAccess.getENUMAccess().getNameAssignment_0(), "rule__ENUM__NameAssignment_0");
					put(grammarAccess.getENUMAccess().getState1Assignment_2(), "rule__ENUM__State1Assignment_2");
					put(grammarAccess.getENUMAccess().getStatesAssignment_3_1(), "rule__ENUM__StatesAssignment_3_1");
					put(grammarAccess.getStateAccess().getStateTraceDirectiveAssignment_0(), "rule__State__StateTraceDirectiveAssignment_0");
					put(grammarAccess.getStateAccess().getStateNameAssignment_1_3(), "rule__State__StateNameAssignment_1_3");
					put(grammarAccess.getStateAccess().getStatesAssignment_1_5_1(), "rule__State__StatesAssignment_1_5_1");
					put(grammarAccess.getStateEntityAccess().getExpressionAssignment_4_0(), "rule__StateEntity__ExpressionAssignment_4_0");
					put(grammarAccess.getTransitionAccess().getEventsAssignment_0_1(), "rule__Transition__EventsAssignment_0_1");
					put(grammarAccess.getTransitionAccess().getAAssignment_0_3(), "rule__Transition__AAssignment_0_3");
					put(grammarAccess.getTransitionAccess().getStateNameAssignment_0_4(), "rule__Transition__StateNameAssignment_0_4");
					put(grammarAccess.getTransitionAccess().getGAssignment_1_1(), "rule__Transition__GAssignment_1_1");
					put(grammarAccess.getTransitionAccess().getAAssignment_1_3(), "rule__Transition__AAssignment_1_3");
					put(grammarAccess.getTransitionAccess().getStateNameAssignment_1_4(), "rule__Transition__StateNameAssignment_1_4");
					put(grammarAccess.getEventDefinitionAccess().getEventIDAssignment_2(), "rule__EventDefinition__EventIDAssignment_2");
					put(grammarAccess.getActionAccess().getCodeAssignment_1(), "rule__Action__CodeAssignment_1");
					put(grammarAccess.getEntryOrExitActionAccess().getTypeAssignment_0_0(), "rule__EntryOrExitAction__TypeAssignment_0_0");
					put(grammarAccess.getEntryOrExitActionAccess().getTypeAssignment_0_1(), "rule__EntryOrExitAction__TypeAssignment_0_1");
					put(grammarAccess.getEntryOrExitActionAccess().getCodeAssignment_2(), "rule__EntryOrExitAction__CodeAssignment_2");
					put(grammarAccess.getActivityAccess().getCodeAssignment_1(), "rule__Activity__CodeAssignment_1");
					put(grammarAccess.getGuardCodeAccess().getNativeExpressionAssignment(), "rule__GuardCode__NativeExpressionAssignment");
					put(grammarAccess.getPositionAccess().getAAssignment_0(), "rule__Position__AAssignment_0");
					put(grammarAccess.getPositionAccess().getCAssignment_1(), "rule__Position__CAssignment_1");
					put(grammarAccess.getClassPositionAccess().getXAssignment_1(), "rule__ClassPosition__XAssignment_1");
					put(grammarAccess.getClassPositionAccess().getYAssignment_2(), "rule__ClassPosition__YAssignment_2");
					put(grammarAccess.getClassPositionAccess().getWidthAssignment_3(), "rule__ClassPosition__WidthAssignment_3");
					put(grammarAccess.getClassPositionAccess().getHeightAssignment_4(), "rule__ClassPosition__HeightAssignment_4");
					put(grammarAccess.getAssociationPositionAccess().getIndexAssignment_1(), "rule__AssociationPosition__IndexAssignment_1");
					put(grammarAccess.getAssociationPositionAccess().getC1Assignment_2(), "rule__AssociationPosition__C1Assignment_2");
					put(grammarAccess.getAssociationPositionAccess().getC2Assignment_3(), "rule__AssociationPosition__C2Assignment_3");
					put(grammarAccess.getCoordinateAccess().getXAssignment_0(), "rule__Coordinate__XAssignment_0");
					put(grammarAccess.getCoordinateAccess().getYAssignment_2(), "rule__Coordinate__YAssignment_2");
					put(grammarAccess.getTraceDirectiveAccess().getTraceStartAssignment_0(), "rule__TraceDirective__TraceStartAssignment_0");
					put(grammarAccess.getTraceDirectiveAccess().getModelElementAssignment_1(), "rule__TraceDirective__ModelElementAssignment_1");
					put(grammarAccess.getTraceDirectiveAccess().getConditionRHSAssignment_2(), "rule__TraceDirective__ConditionRHSAssignment_2");
					put(grammarAccess.getTraceDirectiveAccess().getElementPatternAssignment_3(), "rule__TraceDirective__ElementPatternAssignment_3");
					put(grammarAccess.getTraceCaseAccess().getTraceCaseNameAssignment_1(), "rule__TraceCase__TraceCaseNameAssignment_1");
					put(grammarAccess.getTraceCaseAccess().getTraceDirectiveAssignment_3(), "rule__TraceCase__TraceDirectiveAssignment_3");
					put(grammarAccess.getTraceRecordAccess().getObjectBeingTracedAssignment_0_2(), "rule__TraceRecord__ObjectBeingTracedAssignment_0_2");
					put(grammarAccess.getTraceRecordAccess().getTextOutputAssignment_0_3_1(), "rule__TraceRecord__TextOutputAssignment_0_3_1");
					put(grammarAccess.getCompoundTraceConditionAccess().getOperandAssignment(), "rule__CompoundTraceCondition__OperandAssignment");
					put(grammarAccess.getSimpleTraceConditionAccess().getLhsAssignment_0(), "rule__SimpleTraceCondition__LhsAssignment_0");
					put(grammarAccess.getSimpleTraceConditionAccess().getConditionRHSAssignment_1(), "rule__SimpleTraceCondition__ConditionRHSAssignment_1");
					put(grammarAccess.getConditionRHSAccess().getOperandAssignment_0(), "rule__ConditionRHS__OperandAssignment_0");
					put(grammarAccess.getConditionRHSAccess().getValueAssignment_1(), "rule__ConditionRHS__ValueAssignment_1");
					put(grammarAccess.getModelElementAccess().getExecuteOnEntryAssignment_0_0_0(), "rule__ModelElement__ExecuteOnEntryAssignment_0_0_0");
					put(grammarAccess.getModelElementAccess().getExecuteOnExitAssignment_0_0_1(), "rule__ModelElement__ExecuteOnExitAssignment_0_0_1");
					put(grammarAccess.getModelElementAccess().getCflowAssignment_0_0_2(), "rule__ModelElement__CflowAssignment_0_0_2");
					put(grammarAccess.getModelElementAccess().getAMethodAssignment_0_1(), "rule__ModelElement__AMethodAssignment_0_1");
					put(grammarAccess.getModelElementAccess().getAttributeAssignment_1(), "rule__ModelElement__AttributeAssignment_1");
					put(grammarAccess.getTraceMechanismAccess().getTraceMechanismAssignment_1(), "rule__TraceMechanism__TraceMechanismAssignment_1");
					put(grammarAccess.getBlockAccess().getBlocksAssignment_1(), "rule__Block__BlocksAssignment_1");
					put(grammarAccess.getExpressionListAccess().getExpressionsAssignment_0(), "rule__ExpressionList__ExpressionsAssignment_0");
					put(grammarAccess.getExpressionListAccess().getExpressionsAssignment_1_1(), "rule__ExpressionList__ExpressionsAssignment_1_1");
					put(grammarAccess.getExpressionAccess().getExpression1Assignment_0(), "rule__Expression__Expression1Assignment_0");
					put(grammarAccess.getExpressionAccess().getExpression2Assignment_1_1(), "rule__Expression__Expression2Assignment_1_1");
					put(grammarAccess.getConditionalExpressionAccess().getExpression1Assignment_0(), "rule__ConditionalExpression__Expression1Assignment_0");
					put(grammarAccess.getConditionalExpressionAccess().getExpression2Assignment_1_1(), "rule__ConditionalExpression__Expression2Assignment_1_1");
					put(grammarAccess.getConditionalExpressionAccess().getExpression3Assignment_1_3(), "rule__ConditionalExpression__Expression3Assignment_1_3");
					put(grammarAccess.getConditionalOrExpressionAccess().getExpression1Assignment_0(), "rule__ConditionalOrExpression__Expression1Assignment_0");
					put(grammarAccess.getConditionalOrExpressionAccess().getExpressionRestAssignment_1_1(), "rule__ConditionalOrExpression__ExpressionRestAssignment_1_1");
					put(grammarAccess.getConditionalAndExpressionAccess().getExpression1Assignment_0(), "rule__ConditionalAndExpression__Expression1Assignment_0");
					put(grammarAccess.getConditionalAndExpressionAccess().getExpressionRestAssignment_1_1(), "rule__ConditionalAndExpression__ExpressionRestAssignment_1_1");
					put(grammarAccess.getEqualityExpressionAccess().getExpression1Assignment_0(), "rule__EqualityExpression__Expression1Assignment_0");
					put(grammarAccess.getEqualityExpressionAccess().getExpressionRestAssignment_1_1(), "rule__EqualityExpression__ExpressionRestAssignment_1_1");
					put(grammarAccess.getRelationalExpressionAccess().getExpression1Assignment_0(), "rule__RelationalExpression__Expression1Assignment_0");
					put(grammarAccess.getRelationalExpressionAccess().getExpressionRestAssignment_1_1(), "rule__RelationalExpression__ExpressionRestAssignment_1_1");
					put(grammarAccess.getAdditiveExpressionAccess().getExpression1Assignment_0(), "rule__AdditiveExpression__Expression1Assignment_0");
					put(grammarAccess.getAdditiveExpressionAccess().getExpressionRestAssignment_1_1(), "rule__AdditiveExpression__ExpressionRestAssignment_1_1");
					put(grammarAccess.getMultiplicativeExpressionAccess().getExpression1Assignment_0(), "rule__MultiplicativeExpression__Expression1Assignment_0");
					put(grammarAccess.getMultiplicativeExpressionAccess().getExpressionRestAssignment_1_1(), "rule__MultiplicativeExpression__ExpressionRestAssignment_1_1");
					put(grammarAccess.getUnaryExpressionAccess().getExp1Assignment_0_1(), "rule__UnaryExpression__Exp1Assignment_0_1");
					put(grammarAccess.getUnaryExpressionAccess().getExp1Assignment_1_1(), "rule__UnaryExpression__Exp1Assignment_1_1");
					put(grammarAccess.getUnaryExpressionAccess().getExp1Assignment_2_1(), "rule__UnaryExpression__Exp1Assignment_2_1");
					put(grammarAccess.getUnaryExpressionAccess().getExp1Assignment_3_1(), "rule__UnaryExpression__Exp1Assignment_3_1");
					put(grammarAccess.getUnaryExpressionAccess().getExp2Assignment_4(), "rule__UnaryExpression__Exp2Assignment_4");
					put(grammarAccess.getFunctionDeclarationAccess().getJavaAssignment(), "rule__FunctionDeclaration__JavaAssignment");
					put(grammarAccess.getFunctionDefinitionAccess().getJavaAssignment(), "rule__FunctionDefinition__JavaAssignment");
					put(grammarAccess.getJavaFunctionDeclarationAccess().getReturnTypeAssignment_2_0(), "rule__JavaFunctionDeclaration__ReturnTypeAssignment_2_0");
					put(grammarAccess.getJavaFunctionDeclarationAccess().getReferenceTypeAssignment_2_2(), "rule__JavaFunctionDeclaration__ReferenceTypeAssignment_2_2");
					put(grammarAccess.getJavaFunctionDeclarationAccess().getNameAssignment_3(), "rule__JavaFunctionDeclaration__NameAssignment_3");
					put(grammarAccess.getJavaFunctionDeclarationAccess().getArgListAssignment_4_0_1_0(), "rule__JavaFunctionDeclaration__ArgListAssignment_4_0_1_0");
					put(grammarAccess.getJavaFunctionDeclarationAccess().getArgListIDAssignment_4_0_1_1(), "rule__JavaFunctionDeclaration__ArgListIDAssignment_4_0_1_1");
					put(grammarAccess.getJavaFunctionDeclarationAccess().getArgListAssignment_4_0_1_2_1(), "rule__JavaFunctionDeclaration__ArgListAssignment_4_0_1_2_1");
					put(grammarAccess.getJavaFunctionDeclarationAccess().getArgListIDAssignment_4_0_1_2_2(), "rule__JavaFunctionDeclaration__ArgListIDAssignment_4_0_1_2_2");
					put(grammarAccess.getJavaFunctionDefinitionAccess().getDeclAssignment_0(), "rule__JavaFunctionDefinition__DeclAssignment_0");
					put(grammarAccess.getJavaFunctionDefinitionAccess().getCodeAssignment_1(), "rule__JavaFunctionDefinition__CodeAssignment_1");
					put(grammarAccess.getJavaFunctionCallAccess().getNameAssignment_0(), "rule__JavaFunctionCall__NameAssignment_0");
					put(grammarAccess.getJavaFunctionCallAccess().getArgsAssignment_1_0_1(), "rule__JavaFunctionCall__ArgsAssignment_1_0_1");
					put(grammarAccess.getLocalVariableDeclarationAccess().getTypeAssignment_0(), "rule__LocalVariableDeclaration__TypeAssignment_0");
					put(grammarAccess.getLocalVariableDeclarationAccess().getDecAssignment_1(), "rule__LocalVariableDeclaration__DecAssignment_1");
					put(grammarAccess.getVariableDeclaratorsAccess().getVdAssignment_0(), "rule__VariableDeclarators__VdAssignment_0");
					put(grammarAccess.getVariableDeclaratorsAccess().getVdAssignment_1_1(), "rule__VariableDeclarators__VdAssignment_1_1");
					put(grammarAccess.getVariableDeclaratorAccess().getNameAssignment_0(), "rule__VariableDeclarator__NameAssignment_0");
					put(grammarAccess.getVariableDeclaratorAccess().getExpAssignment_1_1(), "rule__VariableDeclarator__ExpAssignment_1_1");
					put(grammarAccess.getStatementAccess().getConditionAssignment_1_1(), "rule__Statement__ConditionAssignment_1_1");
					put(grammarAccess.getStatementAccess().getState1Assignment_1_2(), "rule__Statement__State1Assignment_1_2");
					put(grammarAccess.getStatementAccess().getState2Assignment_1_3_1(), "rule__Statement__State2Assignment_1_3_1");
					put(grammarAccess.getStatementAccess().getControlAssignment_2_2(), "rule__Statement__ControlAssignment_2_2");
					put(grammarAccess.getStatementAccess().getStateAssignment_2_4(), "rule__Statement__StateAssignment_2_4");
					put(grammarAccess.getStatementAccess().getConditionAssignment_3_1(), "rule__Statement__ConditionAssignment_3_1");
					put(grammarAccess.getStatementAccess().getStateAssignment_3_2(), "rule__Statement__StateAssignment_3_2");
					put(grammarAccess.getStatementAccess().getRetValAssignment_4_1(), "rule__Statement__RetValAssignment_4_1");
					put(grammarAccess.getStatementAccess().getTryBlockAssignment_8_1(), "rule__Statement__TryBlockAssignment_8_1");
					put(grammarAccess.getStatementAccess().getCatchBlockAssignment_8_3(), "rule__Statement__CatchBlockAssignment_8_3");
					put(grammarAccess.getForControlAccess().getInitAssignment_0(), "rule__ForControl__InitAssignment_0");
					put(grammarAccess.getForControlAccess().getConditionAssignment_2(), "rule__ForControl__ConditionAssignment_2");
					put(grammarAccess.getForControlAccess().getUpdateAssignment_4(), "rule__ForControl__UpdateAssignment_4");
					put(grammarAccess.getForInitAccess().getExpressionsAssignment_0_0(), "rule__ForInit__ExpressionsAssignment_0_0");
					put(grammarAccess.getForInitAccess().getExpressionsAssignment_0_1_1(), "rule__ForInit__ExpressionsAssignment_0_1_1");
					put(grammarAccess.getPhpFunctionAccess().getNameAssignment_2(), "rule__PhpFunction__NameAssignment_2");
					put(grammarAccess.getPhpFunctionAccess().getCodeblockAssignment_3(), "rule__PhpFunction__CodeblockAssignment_3");
					put(grammarAccess.getPhpBlockAccess().getCodeAssignment_1(), "rule__PhpBlock__CodeAssignment_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			cruise.umple.ui.contentassist.antlr.internal.InternalUmpleParser typedParser = (cruise.umple.ui.contentassist.antlr.internal.InternalUmpleParser) parser;
			typedParser.entryRuleUmpleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public UmpleGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(UmpleGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
