package cruise.umple.compiler.featureModel;
// This file is generally generated by AI to cover as mush cases as possible
import org.junit.*;
import cruise.umple.compiler.*;
import cruise.umple.compiler.FeatureLink.FeatureConnectingOpType;
import cruise.umple.util.Json;
import cruise.umple.util.JsonParser;
import cruise.umple.parser.ParseResult;

public class FeatureModelJsonTest
{

  // =========================================================================
  // toJSON() tests
  // =========================================================================

  // --- Simple / Normal cases ---

  @Test
  public void toJSON_emptyModel()
  {
    FeatureModel model = new FeatureModel("TestModel");
    String json = model.toJSON();
    Assert.assertNotNull(json);
    Assert.assertTrue(json.contains("\"featureModel\""));
    Assert.assertTrue(json.contains("\"name\":\"TestModel\""));
    Assert.assertTrue(json.contains("\"nodes\":[]"));
    Assert.assertTrue(json.contains("\"links\":[]"));
  }

  @Test
  public void toJSON_singleFeatureLeafNoMixset()
  {
    FeatureModel model = new FeatureModel("M");
    FeatureLeaf leaf = new FeatureLeaf(model);
    leaf.setName("LeafA");

    String json = model.toJSON();
    Assert.assertTrue(json.contains("\"nodeType\":\"FeatureLeaf\""));
    Assert.assertTrue(json.contains("\"name\":\"LeafA\""));
    Assert.assertTrue(json.contains("\"isLeaf\":true"));
    Assert.assertTrue(json.contains("\"isCompoundFeature\":false"));
    Assert.assertTrue(json.contains("\"mixsetOrFileNode\":null"));
  }

  @Test
  public void toJSON_featureLeafWithMixset()
  {
    FeatureModel model = new FeatureModel("M");
    FeatureLeaf leaf = new FeatureLeaf(model);
    leaf.setName("LeafB");
    Mixset mixset = new Mixset("MixsetX");
    mixset.setIsFeature(true);
    mixset.setIsEmpty(false);
    leaf.setMixsetOrFileNode(mixset);

    String json = model.toJSON();
    Assert.assertTrue(json.contains("\"type\":\"Mixset\""));
    Assert.assertTrue(json.contains("\"name\":\"MixsetX\""));
    Assert.assertTrue(json.contains("\"isMixset\":true"));
    Assert.assertTrue(json.contains("\"isFeature\":true"));
    Assert.assertTrue(json.contains("\"isEmpty\":false"));
  }

  @Test
  public void toJSON_featureLeafWithEmptyMixset()
  {
    FeatureModel model = new FeatureModel("M");
    FeatureLeaf leaf = new FeatureLeaf(model);
    leaf.setName("EmptyLeaf");
    Mixset mixset = new Mixset("EmptyMix");
    mixset.setIsFeature(false);
    mixset.setIsEmpty(true);
    leaf.setMixsetOrFileNode(mixset);

    String json = model.toJSON();
    Assert.assertTrue(json.contains("\"isEmpty\":true"));
    Assert.assertTrue(json.contains("\"isFeature\":false"));
  }

  @Test
  public void toJSON_compoundFeatureNodeWithChildren()
  {
    FeatureModel model = new FeatureModel("M");
    CompoundFeatureNode parent = new CompoundFeatureNode(model);
    parent.setName("Parent");
    FeatureLeaf child1 = new FeatureLeaf(model);
    child1.setName("Child1");
    FeatureLeaf child2 = new FeatureLeaf(model);
    child2.setName("Child2");
    parent.addChildFeature(child1);
    parent.addChildFeature(child2);

    String json = model.toJSON();
    Assert.assertTrue(json.contains("\"nodeType\":\"CompoundFeatureNode\""));
    Assert.assertTrue(json.contains("\"isCompoundFeature\":true"));
    Assert.assertTrue(json.contains("\"childFeatureIds\""));
    // Verify child IDs are present
    Assert.assertTrue(json.contains(String.valueOf(child1.getId())));
    Assert.assertTrue(json.contains(String.valueOf(child2.getId())));
  }

  @Test
  public void toJSON_compoundFeatureNodeNoChildren()
  {
    FeatureModel model = new FeatureModel("M");
    CompoundFeatureNode cfn = new CompoundFeatureNode(model);
    cfn.setName("EmptyCompound");

    String json = model.toJSON();
    Assert.assertTrue(json.contains("\"childFeatureIds\":[]"));
  }

  @Test
  public void toJSON_fragmentFeatureLeafWithFragments()
  {
    FeatureModel model = new FeatureModel("M");
    FragmentFeatureLeaf ffl = new FragmentFeatureLeaf(model);
    ffl.setName("FragLeaf");
    MixsetFragment frag = new MixsetFragment(null, 42, "class Foo { }");
    ffl.addMixsetFragment(frag);

    String json = model.toJSON();
    Assert.assertTrue(json.contains("\"nodeType\":\"FragmentFeatureLeaf\""));
    Assert.assertTrue(json.contains("\"fragments\""));
    Assert.assertTrue(json.contains("\"line\":42"));
    Assert.assertTrue(json.contains("\"bodyLength\":13")); // "class Foo { }".length() == 13
  }

  @Test
  public void toJSON_fragmentFeatureLeafNoFragments()
  {
    FeatureModel model = new FeatureModel("M");
    FragmentFeatureLeaf ffl = new FragmentFeatureLeaf(model);
    ffl.setName("EmptyFragLeaf");

    String json = model.toJSON();
    Assert.assertTrue(json.contains("\"fragments\":[]"));
  }

  @Test
  public void toJSON_plainFeatureNode()
  {
    FeatureModel model = new FeatureModel("M");
    FeatureNode node = new FeatureNode(model);
    node.setName("PlainNode");

    String json = model.toJSON();
    Assert.assertTrue(json.contains("\"nodeType\":\"FeatureNode\""));
    Assert.assertTrue(json.contains("\"isLeaf\":false"));
    Assert.assertTrue(json.contains("\"isCompoundFeature\":false"));
    // Should NOT contain subtype-specific fields
    Assert.assertFalse(json.contains("\"mixsetOrFileNode\""));
    Assert.assertFalse(json.contains("\"childFeatureIds\""));
    Assert.assertFalse(json.contains("\"fragments\""));
  }

  @Test
  public void toJSON_basicFeatureLink()
  {
    FeatureModel model = new FeatureModel("M");
    FeatureLeaf src = new FeatureLeaf(model);
    src.setName("Src");
    FeatureLeaf tgt = new FeatureLeaf(model);
    tgt.setName("Tgt");

    FeatureLink link = new FeatureLink();
    link.setSourceFeatureNode(src);
    link.setTargetFeatureNode(tgt);
    link.setFeatureConnectingOpType(FeatureConnectingOpType.Mandatory);
    link.setIsSub(true);
    link.setFeatureModel(model);

    String json = model.toJSON();
    Assert.assertTrue(json.contains("\"linkType\":\"FeatureLink\""));
    Assert.assertTrue(json.contains("\"opType\":\"Mandatory\""));
    Assert.assertTrue(json.contains("\"isSub\":true"));
    Assert.assertTrue(json.contains("\"sourceNodeId\":" + src.getId()));
    Assert.assertTrue(json.contains("\"targetNodeId\":" + tgt.getId()));
    // Basic FeatureLink should NOT have bounds
    Assert.assertFalse(json.contains("\"lowerBound\""));
  }

  @Test
  public void toJSON_multiplicityLink()
  {
    FeatureModel model = new FeatureModel("M");
    FeatureLeaf src = new FeatureLeaf(model);
    src.setName("Src");
    FeatureLeaf tgt = new FeatureLeaf(model);
    tgt.setName("Tgt");

    MultiplicityFeatureConnectingOpType multLink = new MultiplicityFeatureConnectingOpType();
    multLink.setSourceFeatureNode(src);
    multLink.setTargetFeatureNode(tgt);
    multLink.getMultiplicity().setRange("2", "5");
    multLink.setFeatureModel(model);

    String json = model.toJSON();
    Assert.assertTrue(json.contains("\"linkType\":\"MultiplicityFeatureConnectingOpType\""));
    Assert.assertTrue(json.contains("\"opType\":\"Multiplicity\""));
    Assert.assertTrue(json.contains("\"lowerBound\":2"));
    Assert.assertTrue(json.contains("\"upperBound\":5"));
  }

  @Test
  public void toJSON_xorLink()
  {
    FeatureModel model = new FeatureModel("M");
    FeatureLeaf src = new FeatureLeaf(model);
    src.setName("Src");
    FeatureLeaf tgt = new FeatureLeaf(model);
    tgt.setName("Tgt");

    XORFeatureConnectingOpType xorLink = new XORFeatureConnectingOpType();
    xorLink.setSourceFeatureNode(src);
    xorLink.setTargetFeatureNode(tgt);
    xorLink.setFeatureModel(model);

    String json = model.toJSON();
    Assert.assertTrue(json.contains("\"linkType\":\"XORFeatureConnectingOpType\""));
    Assert.assertTrue(json.contains("\"opType\":\"XOR\""));
    Assert.assertTrue(json.contains("\"lowerBound\":1"));
    Assert.assertTrue(json.contains("\"upperBound\":1"));
  }

  @Test
  public void toJSON_allOpTypes()
  {
    // Verify each FeatureConnectingOpType serializes its name correctly
    for (FeatureConnectingOpType opType : FeatureConnectingOpType.values())
    {
      FeatureModel model = new FeatureModel("M");
      FeatureLeaf src = new FeatureLeaf(model);
      src.setName("S");
      FeatureLeaf tgt = new FeatureLeaf(model);
      tgt.setName("T");

      FeatureLink link = new FeatureLink();
      link.setFeatureConnectingOpType(opType);
      link.setSourceFeatureNode(src);
      link.setTargetFeatureNode(tgt);
      link.setFeatureModel(model);

      String json = model.toJSON();
      Assert.assertTrue("opType " + opType.name() + " not found in JSON",
          json.contains("\"opType\":\"" + opType.name() + "\""));
    }
  }

  @Test
  public void toJSON_multipleNodesAndLinks()
  {
    FeatureModel model = new FeatureModel("Complex");
    FeatureLeaf a = new FeatureLeaf(model);
    a.setName("A");
    FeatureLeaf b = new FeatureLeaf(model);
    b.setName("B");
    CompoundFeatureNode c = new CompoundFeatureNode(model);
    c.setName("C");
    c.addChildFeature(a);
    c.addChildFeature(b);

    FeatureLink link1 = new FeatureLink();
    link1.setSourceFeatureNode(c);
    link1.setTargetFeatureNode(a);
    link1.setFeatureConnectingOpType(FeatureConnectingOpType.Mandatory);
    link1.setIsSub(true);
    link1.setFeatureModel(model);

    FeatureLink link2 = new FeatureLink();
    link2.setSourceFeatureNode(c);
    link2.setTargetFeatureNode(b);
    link2.setFeatureConnectingOpType(FeatureConnectingOpType.Optional);
    link2.setIsSub(true);
    link2.setFeatureModel(model);

    String json = model.toJSON();
    Assert.assertEquals(3, model.numberOfNode());
    Assert.assertEquals(2, model.numberOfFeaturelink());
    Assert.assertTrue(json.contains("\"name\":\"Complex\""));
    Assert.assertTrue(json.contains("\"Mandatory\""));
    Assert.assertTrue(json.contains("\"Optional\""));
  }

  @Test
  public void toJSON_nodeUniqueNameFormat()
  {
    FeatureModel model = new FeatureModel("M");
    FeatureNode node = new FeatureNode(model);
    node.setName("TestNode");
    // FeatureNode.getUniqueFeatureNodeName() returns "name_id"
    String expectedUnique = "TestNode_" + node.getId();

    String json = model.toJSON();
    Assert.assertTrue(json.contains("\"uniqueName\":\"" + expectedUnique + "\""));
  }

  @Test
  public void toJSON_featureLeafUniqueNameIsJustName()
  {
    FeatureModel model = new FeatureModel("M");
    FeatureLeaf leaf = new FeatureLeaf(model);
    leaf.setName("MyLeaf");
    // FeatureLeaf overrides getUniqueFeatureNodeName() to return just the name

    String json = model.toJSON();
    Assert.assertTrue(json.contains("\"uniqueName\":\"MyLeaf\""));
  }

  // --- Edge cases ---

  @Test
  public void toJSON_nullNodeName()
  {
    FeatureModel model = new FeatureModel("M");
    FeatureNode node = new FeatureNode(model);
    // Name is lazy (not set), so getName() returns null

    String json = model.toJSON();
    Assert.assertTrue(json.contains("\"name\":null"));
  }

  @Test
  public void toJSON_emptyStringModelName()
  {
    FeatureModel model = new FeatureModel("");
    String json = model.toJSON();
    Assert.assertTrue(json.contains("\"name\":\"\""));
  }

  @Test
  public void toJSON_specialCharsInName()
  {
    FeatureModel model = new FeatureModel("Test\"Model\\With\nSpecial");
    String json = model.toJSON();
    // Json.escapeJsonString handles these
    Assert.assertTrue(json.contains("Test\\\"Model\\\\With\\nSpecial"));
  }

  @Test
  public void toJSON_validJsonStructure()
  {
    FeatureModel model = new FeatureModel("Validation");
    FeatureLeaf leaf = new FeatureLeaf(model);
    leaf.setName("V");

    String json = model.toJSON();
    // Should be parseable by JsonParser
    JsonParser parser = new JsonParser("test");
    ParseResult result = parser.parse("json", json);
    Assert.assertTrue("toJSON output should be valid JSON", result.getWasSuccess());
  }

  @Test
  public void toJSON_linkWithNullSourceTarget()
  {
    FeatureModel model = new FeatureModel("M");
    FeatureLink link = new FeatureLink();
    // source and target not set (null)
    link.setFeatureModel(model);

    String json = model.toJSON();
    Assert.assertTrue(json.contains("\"sourceNodeId\":null"));
    Assert.assertTrue(json.contains("\"targetNodeId\":null"));
  }

  @Test
  public void toJSON_fragmentWithNullBody()
  {
    FeatureModel model = new FeatureModel("M");
    FragmentFeatureLeaf ffl = new FragmentFeatureLeaf(model);
    ffl.setName("Frag");
    MixsetFragment frag = new MixsetFragment(null, 0, null);
    ffl.addMixsetFragment(frag);

    String json = model.toJSON();
    Assert.assertTrue(json.contains("\"bodyLength\":0"));
    Assert.assertTrue(json.contains("\"file\":null"));
  }

  @Test
  public void toJSON_fragmentWithNullOriginalFile()
  {
    FeatureModel model = new FeatureModel("M");
    FragmentFeatureLeaf ffl = new FragmentFeatureLeaf(model);
    ffl.setName("Frag");
    MixsetFragment frag = new MixsetFragment(null, 10, "body content");
    ffl.addMixsetFragment(frag);

    String json = model.toJSON();
    Assert.assertTrue(json.contains("\"file\":null"));
    Assert.assertTrue(json.contains("\"line\":10"));
  }

  @Test
  public void toJSON_mixsetWithNullUseUmpleFile()
  {
    FeatureModel model = new FeatureModel("M");
    FeatureLeaf leaf = new FeatureLeaf(model);
    leaf.setName("L");
    Mixset mixset = new Mixset("Mix");
    // useUmpleFile defaults to null
    leaf.setMixsetOrFileNode(mixset);

    String json = model.toJSON();
    Assert.assertTrue(json.contains("\"useUmpleFile\":null"));
  }

  // =========================================================================
  // fromJSON() tests
  // =========================================================================

  // --- Simple / Normal cases ---

  @Test
  public void fromJSON_emptyModel()
  {
    String json = "{\"featureModel\":{\"name\":\"TestModel\",\"nodes\":[],\"links\":[]}}";
    FeatureModel model = FeatureModel.fromJSON(json);
    Assert.assertNotNull(model);
    Assert.assertEquals("TestModel", model.getName());
    Assert.assertEquals(0, model.numberOfNode());
    Assert.assertEquals(0, model.numberOfFeaturelink());
  }

  @Test
  public void fromJSON_singleFeatureLeaf()
  {
    String json = "{\"featureModel\":{\"name\":\"M\",\"nodes\":[{\"id\":100,\"uniqueName\":\"LeafA\",\"name\":\"LeafA\",\"nodeType\":\"FeatureLeaf\",\"isLeaf\":true,\"isCompoundFeature\":false,\"mixsetOrFileNode\":null}],\"links\":[]}}";
    FeatureModel model = FeatureModel.fromJSON(json);
    Assert.assertNotNull(model);
    Assert.assertEquals(1, model.numberOfNode());
    FeatureNode node = model.getNode(0);
    Assert.assertTrue(node instanceof FeatureLeaf);
    Assert.assertEquals("LeafA", node.getName());
    Assert.assertEquals(100, node.getId());
    Assert.assertTrue(node.getIsLeaf());
  }

  @Test
  public void fromJSON_featureLeafWithMixset()
  {
    String json = "{\"featureModel\":{\"name\":\"M\",\"nodes\":[{\"id\":1,\"uniqueName\":\"L\",\"name\":\"L\",\"nodeType\":\"FeatureLeaf\",\"isLeaf\":true,\"isCompoundFeature\":false,\"mixsetOrFileNode\":{\"type\":\"Mixset\",\"name\":\"MixA\",\"isMixset\":true,\"isFeature\":true,\"isEmpty\":false,\"useUmpleFile\":null,\"useUmpleLine\":0}}],\"links\":[]}}";
    FeatureModel model = FeatureModel.fromJSON(json);
    FeatureLeaf leaf = (FeatureLeaf) model.getNode(0);
    Assert.assertTrue(leaf.hasMixsetOrFileNode());
    MixsetOrFile mof = leaf.getMixsetOrFileNode();
    Assert.assertTrue(mof instanceof Mixset);
    Mixset mixset = (Mixset) mof;
    Assert.assertEquals("MixA", mixset.getMixsetName());
    Assert.assertTrue(mixset.getIsFeature());
    Assert.assertFalse(mixset.getIsEmpty());
  }

  @Test
  public void fromJSON_compoundFeatureNodeWithChildren()
  {
    String json = "{\"featureModel\":{\"name\":\"M\",\"nodes\":["
        + "{\"id\":10,\"uniqueName\":\"Child1\",\"name\":\"Child1\",\"nodeType\":\"FeatureLeaf\",\"isLeaf\":true,\"isCompoundFeature\":false,\"mixsetOrFileNode\":null},"
        + "{\"id\":11,\"uniqueName\":\"Child2\",\"name\":\"Child2\",\"nodeType\":\"FeatureLeaf\",\"isLeaf\":true,\"isCompoundFeature\":false,\"mixsetOrFileNode\":null},"
        + "{\"id\":12,\"uniqueName\":\"Parent_12\",\"name\":\"Parent\",\"nodeType\":\"CompoundFeatureNode\",\"isLeaf\":false,\"isCompoundFeature\":true,\"childFeatureIds\":[10,11]}"
        + "],\"links\":[]}}";
    FeatureModel model = FeatureModel.fromJSON(json);
    Assert.assertEquals(3, model.numberOfNode());

    // Find CompoundFeatureNode
    CompoundFeatureNode parent = null;
    for (FeatureNode n : model.getNode())
    {
      if (n instanceof CompoundFeatureNode) { parent = (CompoundFeatureNode) n; }
    }
    Assert.assertNotNull(parent);
    Assert.assertEquals("Parent", parent.getName());
    Assert.assertEquals(2, parent.numberOfChildFeatures());
  }

  @Test
  public void fromJSON_fragmentFeatureLeaf()
  {
    String json = "{\"featureModel\":{\"name\":\"M\",\"nodes\":[{\"id\":20,\"uniqueName\":\"Frag_20\",\"name\":\"Frag\",\"nodeType\":\"FragmentFeatureLeaf\",\"isLeaf\":true,\"isCompoundFeature\":false,\"fragments\":[{\"file\":null,\"line\":5,\"bodyLength\":100}]}],\"links\":[]}}";
    FeatureModel model = FeatureModel.fromJSON(json);
    Assert.assertEquals(1, model.numberOfNode());
    Assert.assertTrue(model.getNode(0) instanceof FragmentFeatureLeaf);
    Assert.assertEquals("Frag", model.getNode(0).getName());
  }

  @Test
  public void fromJSON_plainFeatureNode()
  {
    String json = "{\"featureModel\":{\"name\":\"M\",\"nodes\":[{\"id\":30,\"uniqueName\":\"Plain_30\",\"name\":\"Plain\",\"nodeType\":\"FeatureNode\",\"isLeaf\":false,\"isCompoundFeature\":false}],\"links\":[]}}";
    FeatureModel model = FeatureModel.fromJSON(json);
    Assert.assertEquals(1, model.numberOfNode());
    FeatureNode node = model.getNode(0);
    Assert.assertFalse(node instanceof FeatureLeaf);
    Assert.assertFalse(node instanceof CompoundFeatureNode);
    Assert.assertFalse(node instanceof FragmentFeatureLeaf);
    Assert.assertEquals("Plain", node.getName());
    Assert.assertEquals(30, node.getId());
  }

  @Test
  public void fromJSON_basicLink()
  {
    String json = "{\"featureModel\":{\"name\":\"M\",\"nodes\":["
        + "{\"id\":1,\"uniqueName\":\"A\",\"name\":\"A\",\"nodeType\":\"FeatureLeaf\",\"isLeaf\":true,\"isCompoundFeature\":false,\"mixsetOrFileNode\":null},"
        + "{\"id\":2,\"uniqueName\":\"B\",\"name\":\"B\",\"nodeType\":\"FeatureLeaf\",\"isLeaf\":true,\"isCompoundFeature\":false,\"mixsetOrFileNode\":null}"
        + "],\"links\":["
        + "{\"sourceNodeId\":1,\"targetNodeId\":2,\"linkType\":\"FeatureLink\",\"opType\":\"Mandatory\",\"isSub\":true}"
        + "]}}";
    FeatureModel model = FeatureModel.fromJSON(json);
    Assert.assertEquals(1, model.numberOfFeaturelink());
    FeatureLink link = model.getFeaturelink(0);
    Assert.assertEquals(FeatureConnectingOpType.Mandatory, link.getFeatureConnectingOpType());
    Assert.assertTrue(link.getIsSub());
    Assert.assertEquals("A", link.getSourceFeatureNode().getName());
    Assert.assertEquals("B", link.getTargetFeatureNode().getName());
  }

  @Test
  public void fromJSON_multiplicityLink()
  {
    String json = "{\"featureModel\":{\"name\":\"M\",\"nodes\":["
        + "{\"id\":1,\"uniqueName\":\"A\",\"name\":\"A\",\"nodeType\":\"FeatureLeaf\",\"isLeaf\":true,\"isCompoundFeature\":false,\"mixsetOrFileNode\":null},"
        + "{\"id\":2,\"uniqueName\":\"B\",\"name\":\"B\",\"nodeType\":\"FeatureLeaf\",\"isLeaf\":true,\"isCompoundFeature\":false,\"mixsetOrFileNode\":null}"
        + "],\"links\":["
        + "{\"sourceNodeId\":1,\"targetNodeId\":2,\"linkType\":\"MultiplicityFeatureConnectingOpType\",\"opType\":\"Multiplicity\",\"isSub\":false,\"lowerBound\":2,\"upperBound\":5}"
        + "]}}";
    FeatureModel model = FeatureModel.fromJSON(json);
    FeatureLink link = model.getFeaturelink(0);
    Assert.assertTrue(link instanceof MultiplicityFeatureConnectingOpType);
    MultiplicityFeatureConnectingOpType multLink = (MultiplicityFeatureConnectingOpType) link;
    Assert.assertEquals(2, multLink.getMultiplicity().getLowerBound());
    Assert.assertEquals(5, multLink.getMultiplicity().getUpperBound());
  }

  @Test
  public void fromJSON_xorLink()
  {
    String json = "{\"featureModel\":{\"name\":\"M\",\"nodes\":["
        + "{\"id\":1,\"uniqueName\":\"A\",\"name\":\"A\",\"nodeType\":\"FeatureLeaf\",\"isLeaf\":true,\"isCompoundFeature\":false,\"mixsetOrFileNode\":null},"
        + "{\"id\":2,\"uniqueName\":\"B\",\"name\":\"B\",\"nodeType\":\"FeatureLeaf\",\"isLeaf\":true,\"isCompoundFeature\":false,\"mixsetOrFileNode\":null}"
        + "],\"links\":["
        + "{\"sourceNodeId\":1,\"targetNodeId\":2,\"linkType\":\"XORFeatureConnectingOpType\",\"opType\":\"XOR\",\"isSub\":false,\"lowerBound\":1,\"upperBound\":1}"
        + "]}}";
    FeatureModel model = FeatureModel.fromJSON(json);
    FeatureLink link = model.getFeaturelink(0);
    Assert.assertTrue(link instanceof XORFeatureConnectingOpType);
    Assert.assertEquals(FeatureConnectingOpType.XOR, link.getFeatureConnectingOpType());
  }

  @Test
  public void fromJSON_multipleLinks()
  {
    String json = "{\"featureModel\":{\"name\":\"M\",\"nodes\":["
        + "{\"id\":1,\"uniqueName\":\"A\",\"name\":\"A\",\"nodeType\":\"FeatureLeaf\",\"isLeaf\":true,\"isCompoundFeature\":false,\"mixsetOrFileNode\":null},"
        + "{\"id\":2,\"uniqueName\":\"B\",\"name\":\"B\",\"nodeType\":\"FeatureLeaf\",\"isLeaf\":true,\"isCompoundFeature\":false,\"mixsetOrFileNode\":null},"
        + "{\"id\":3,\"uniqueName\":\"C\",\"name\":\"C\",\"nodeType\":\"FeatureLeaf\",\"isLeaf\":true,\"isCompoundFeature\":false,\"mixsetOrFileNode\":null}"
        + "],\"links\":["
        + "{\"sourceNodeId\":1,\"targetNodeId\":2,\"linkType\":\"FeatureLink\",\"opType\":\"Include\",\"isSub\":false},"
        + "{\"sourceNodeId\":1,\"targetNodeId\":3,\"linkType\":\"FeatureLink\",\"opType\":\"Exclude\",\"isSub\":false}"
        + "]}}";
    FeatureModel model = FeatureModel.fromJSON(json);
    Assert.assertEquals(2, model.numberOfFeaturelink());
    Assert.assertEquals(FeatureConnectingOpType.Include, model.getFeaturelink(0).getFeatureConnectingOpType());
    Assert.assertEquals(FeatureConnectingOpType.Exclude, model.getFeaturelink(1).getFeatureConnectingOpType());
  }

  // --- Edge cases ---

  @Test
  public void fromJSON_nullInput()
  {
    FeatureModel model = FeatureModel.fromJSON(null);
    Assert.assertNull(model);
  }

  @Test
  public void fromJSON_emptyString()
  {
    FeatureModel model = FeatureModel.fromJSON("");
    Assert.assertNull(model);
  }

  @Test
  public void fromJSON_invalidJson()
  {
    FeatureModel model = FeatureModel.fromJSON("not json at all");
    Assert.assertNull(model);
  }

  @Test
  public void fromJSON_malformedJson()
  {
    // JsonParser is lenient, so use input that truly fails parsing
    FeatureModel model = FeatureModel.fromJSON("{{{");
    Assert.assertNull(model);
  }

  @Test
  public void fromJSON_missingFeatureModelKey()
  {
    FeatureModel model = FeatureModel.fromJSON("{\"other\":{\"name\":\"X\"}}");
    Assert.assertNull(model);
  }

  @Test
  public void fromJSON_missingName()
  {
    String json = "{\"featureModel\":{\"nodes\":[],\"links\":[]}}";
    FeatureModel model = FeatureModel.fromJSON(json);
    Assert.assertNotNull(model);
    Assert.assertEquals("", model.getName());
  }

  @Test
  public void fromJSON_missingNodesArray()
  {
    String json = "{\"featureModel\":{\"name\":\"M\",\"links\":[]}}";
    FeatureModel model = FeatureModel.fromJSON(json);
    Assert.assertNotNull(model);
    Assert.assertEquals(0, model.numberOfNode());
  }

  @Test
  public void fromJSON_missingLinksArray()
  {
    String json = "{\"featureModel\":{\"name\":\"M\",\"nodes\":[]}}";
    FeatureModel model = FeatureModel.fromJSON(json);
    Assert.assertNotNull(model);
    Assert.assertEquals(0, model.numberOfFeaturelink());
  }

  @Test
  public void fromJSON_emptyMixsetName()
  {
    String json = "{\"featureModel\":{\"name\":\"M\",\"nodes\":[{\"id\":1,\"uniqueName\":\"L\",\"name\":\"L\",\"nodeType\":\"FeatureLeaf\",\"isLeaf\":true,\"isCompoundFeature\":false,\"mixsetOrFileNode\":{\"type\":\"Mixset\",\"name\":\"\",\"isMixset\":true,\"isFeature\":false,\"isEmpty\":false,\"useUmpleFile\":null,\"useUmpleLine\":0}}],\"links\":[]}}";
    FeatureModel model = FeatureModel.fromJSON(json);
    FeatureLeaf leaf = (FeatureLeaf) model.getNode(0);
    Mixset mixset = (Mixset) leaf.getMixsetOrFileNode();
    Assert.assertEquals("", mixset.getMixsetName());
  }

  @Test
  public void fromJSON_compoundNodeChildIdNotFound()
  {
    // childFeatureIds references a node ID that doesn't exist — should not crash
    String json = "{\"featureModel\":{\"name\":\"M\",\"nodes\":["
        + "{\"id\":1,\"uniqueName\":\"P_1\",\"name\":\"P\",\"nodeType\":\"CompoundFeatureNode\",\"isLeaf\":false,\"isCompoundFeature\":true,\"childFeatureIds\":[999]}"
        + "],\"links\":[]}}";
    FeatureModel model = FeatureModel.fromJSON(json);
    Assert.assertNotNull(model);
    CompoundFeatureNode cfn = (CompoundFeatureNode) model.getNode(0);
    Assert.assertEquals(0, cfn.numberOfChildFeatures()); // 999 not found, skipped
  }

  @Test
  public void fromJSON_linkWithUnknownNodeIds()
  {
    // Link references node IDs that don't exist — should not crash
    String json = "{\"featureModel\":{\"name\":\"M\",\"nodes\":[],\"links\":["
        + "{\"sourceNodeId\":888,\"targetNodeId\":999,\"linkType\":\"FeatureLink\",\"opType\":\"Include\",\"isSub\":false}"
        + "]}}";
    FeatureModel model = FeatureModel.fromJSON(json);
    Assert.assertNotNull(model);
    Assert.assertEquals(1, model.numberOfFeaturelink());
    // Source and target should be null since IDs don't match any node
    Assert.assertFalse(model.getFeaturelink(0).hasSourceFeatureNode());
    Assert.assertFalse(model.getFeaturelink(0).hasTargetFeatureNode());
  }

  @Test
  public void fromJSON_mixsetOrFileNodeIsUmpleFileType()
  {
    // UmpleFile type is not reconstructed — leaf should have no mixsetOrFileNode
    String json = "{\"featureModel\":{\"name\":\"M\",\"nodes\":[{\"id\":1,\"uniqueName\":\"L\",\"name\":\"L\",\"nodeType\":\"FeatureLeaf\",\"isLeaf\":true,\"isCompoundFeature\":false,\"mixsetOrFileNode\":{\"type\":\"UmpleFile\",\"name\":\"test\",\"isMixset\":false,\"useUmpleFile\":null,\"useUmpleLine\":0}}],\"links\":[]}}";
    FeatureModel model = FeatureModel.fromJSON(json);
    FeatureLeaf leaf = (FeatureLeaf) model.getNode(0);
    Assert.assertFalse(leaf.hasMixsetOrFileNode());
  }

  // =========================================================================
  // Round-trip tests (toJSON -> fromJSON)
  // =========================================================================

  @Test
  public void roundTrip_emptyModel()
  {
    FeatureModel original = new FeatureModel("RoundTrip");
    String json = original.toJSON();
    FeatureModel restored = FeatureModel.fromJSON(json);
    Assert.assertNotNull(restored);
    Assert.assertEquals(original.getName(), restored.getName());
    Assert.assertEquals(original.numberOfNode(), restored.numberOfNode());
    Assert.assertEquals(original.numberOfFeaturelink(), restored.numberOfFeaturelink());
  }

  @Test
  public void roundTrip_featureLeafWithMixset()
  {
    FeatureModel original = new FeatureModel("RT");
    FeatureLeaf leaf = new FeatureLeaf(original);
    leaf.setName("Feature1");
    Mixset mixset = new Mixset("Mix1");
    mixset.setIsFeature(true);
    mixset.setIsEmpty(false);
    leaf.setMixsetOrFileNode(mixset);

    String json = original.toJSON();
    FeatureModel restored = FeatureModel.fromJSON(json);

    Assert.assertEquals(1, restored.numberOfNode());
    FeatureLeaf restoredLeaf = (FeatureLeaf) restored.getNode(0);
    Assert.assertEquals("Feature1", restoredLeaf.getName());
    Assert.assertTrue(restoredLeaf.hasMixsetOrFileNode());
    Mixset restoredMixset = (Mixset) restoredLeaf.getMixsetOrFileNode();
    Assert.assertEquals("Mix1", restoredMixset.getMixsetName());
    Assert.assertTrue(restoredMixset.getIsFeature());
    Assert.assertFalse(restoredMixset.getIsEmpty());
  }

  @Test
  public void roundTrip_compoundFeatureWithLinks()
  {
    FeatureModel original = new FeatureModel("RT");
    CompoundFeatureNode parent = new CompoundFeatureNode(original);
    parent.setName("Parent");
    FeatureLeaf child1 = new FeatureLeaf(original);
    child1.setName("C1");
    FeatureLeaf child2 = new FeatureLeaf(original);
    child2.setName("C2");
    parent.addChildFeature(child1);
    parent.addChildFeature(child2);

    FeatureLink link = new FeatureLink();
    link.setSourceFeatureNode(parent);
    link.setTargetFeatureNode(child1);
    link.setFeatureConnectingOpType(FeatureConnectingOpType.Mandatory);
    link.setIsSub(true);
    link.setFeatureModel(original);

    String json = original.toJSON();
    FeatureModel restored = FeatureModel.fromJSON(json);

    Assert.assertEquals(3, restored.numberOfNode());
    Assert.assertEquals(1, restored.numberOfFeaturelink());

    // Find the compound node
    CompoundFeatureNode restoredParent = null;
    for (FeatureNode n : restored.getNode())
    {
      if (n instanceof CompoundFeatureNode) { restoredParent = (CompoundFeatureNode) n; }
    }
    Assert.assertNotNull(restoredParent);
    Assert.assertEquals(2, restoredParent.numberOfChildFeatures());

    FeatureLink restoredLink = restored.getFeaturelink(0);
    Assert.assertEquals(FeatureConnectingOpType.Mandatory, restoredLink.getFeatureConnectingOpType());
    Assert.assertTrue(restoredLink.getIsSub());
  }

  @Test
  public void roundTrip_multiplicityLink()
  {
    FeatureModel original = new FeatureModel("RT");
    FeatureLeaf src = new FeatureLeaf(original);
    src.setName("S");
    FeatureLeaf tgt = new FeatureLeaf(original);
    tgt.setName("T");

    MultiplicityFeatureConnectingOpType multLink = new MultiplicityFeatureConnectingOpType();
    multLink.setSourceFeatureNode(src);
    multLink.setTargetFeatureNode(tgt);
    multLink.getMultiplicity().setRange("3", "7");
    multLink.setFeatureModel(original);

    String json = original.toJSON();
    FeatureModel restored = FeatureModel.fromJSON(json);

    MultiplicityFeatureConnectingOpType restoredLink = (MultiplicityFeatureConnectingOpType) restored.getFeaturelink(0);
    Assert.assertEquals(3, restoredLink.getMultiplicity().getLowerBound());
    Assert.assertEquals(7, restoredLink.getMultiplicity().getUpperBound());
  }

  @Test
  public void roundTrip_xorLink()
  {
    FeatureModel original = new FeatureModel("RT");
    FeatureLeaf src = new FeatureLeaf(original);
    src.setName("S");
    FeatureLeaf tgt = new FeatureLeaf(original);
    tgt.setName("T");

    XORFeatureConnectingOpType xorLink = new XORFeatureConnectingOpType();
    xorLink.setSourceFeatureNode(src);
    xorLink.setTargetFeatureNode(tgt);
    xorLink.setFeatureModel(original);

    String json = original.toJSON();
    FeatureModel restored = FeatureModel.fromJSON(json);

    Assert.assertTrue(restored.getFeaturelink(0) instanceof XORFeatureConnectingOpType);
    XORFeatureConnectingOpType restoredXor = (XORFeatureConnectingOpType) restored.getFeaturelink(0);
    Assert.assertEquals(1, restoredXor.getMultiplicity().getLowerBound());
    Assert.assertEquals(1, restoredXor.getMultiplicity().getUpperBound());
  }

  @Test
  public void roundTrip_complexModelPreservesStructure()
  {
    FeatureModel original = new FeatureModel("FullModel");

    // Create a tree: Root (compound) -> [A (leaf+mixset), B (leaf), C (fragment)]
    CompoundFeatureNode root = new CompoundFeatureNode(original);
    root.setName("Root");

    FeatureLeaf a = new FeatureLeaf(original);
    a.setName("A");
    Mixset mixA = new Mixset("MixA");
    mixA.setIsFeature(true);
    a.setMixsetOrFileNode(mixA);

    FeatureLeaf b = new FeatureLeaf(original);
    b.setName("B");

    FragmentFeatureLeaf c = new FragmentFeatureLeaf(original);
    c.setName("C");

    root.addChildFeature(a);
    root.addChildFeature(b);
    root.addChildFeature(c);

    // Mandatory link root->a
    FeatureLink mandLink = new FeatureLink();
    mandLink.setSourceFeatureNode(root);
    mandLink.setTargetFeatureNode(a);
    mandLink.setFeatureConnectingOpType(FeatureConnectingOpType.Mandatory);
    mandLink.setIsSub(true);
    mandLink.setFeatureModel(original);

    // Optional link root->b
    FeatureLink optLink = new FeatureLink();
    optLink.setSourceFeatureNode(root);
    optLink.setTargetFeatureNode(b);
    optLink.setFeatureConnectingOpType(FeatureConnectingOpType.Optional);
    optLink.setIsSub(true);
    optLink.setFeatureModel(original);

    // XOR link root->c
    XORFeatureConnectingOpType xorLink = new XORFeatureConnectingOpType();
    xorLink.setSourceFeatureNode(root);
    xorLink.setTargetFeatureNode(c);
    xorLink.setFeatureModel(original);

    String json = original.toJSON();
    FeatureModel restored = FeatureModel.fromJSON(json);

    Assert.assertEquals("FullModel", restored.getName());
    Assert.assertEquals(4, restored.numberOfNode());
    Assert.assertEquals(3, restored.numberOfFeaturelink());

    // Verify node types survive round-trip
    int leafCount = 0, compoundCount = 0, fragmentCount = 0;
    for (FeatureNode n : restored.getNode())
    {
      if (n instanceof CompoundFeatureNode) { compoundCount++; }
      else if (n instanceof FragmentFeatureLeaf) { fragmentCount++; }
      else if (n instanceof FeatureLeaf) { leafCount++; }
    }
    Assert.assertEquals(2, leafCount);
    Assert.assertEquals(1, compoundCount);
    Assert.assertEquals(1, fragmentCount);
  }

  @Test
  public void roundTrip_doubleRoundTrip()
  {
    // Serialize -> deserialize -> serialize -> deserialize should be stable
    FeatureModel original = new FeatureModel("Double");
    FeatureLeaf leaf = new FeatureLeaf(original);
    leaf.setName("Leaf");
    Mixset mix = new Mixset("M");
    mix.setIsFeature(true);
    leaf.setMixsetOrFileNode(mix);

    FeatureLink link = new FeatureLink();
    link.setFeatureConnectingOpType(FeatureConnectingOpType.Conjunctive);
    link.setIsSub(false);
    link.setFeatureModel(original);

    String json1 = original.toJSON();
    FeatureModel restored1 = FeatureModel.fromJSON(json1);
    String json2 = restored1.toJSON();
    FeatureModel restored2 = FeatureModel.fromJSON(json2);

    Assert.assertEquals(restored1.getName(), restored2.getName());
    Assert.assertEquals(restored1.numberOfNode(), restored2.numberOfNode());
    Assert.assertEquals(restored1.numberOfFeaturelink(), restored2.numberOfFeaturelink());
  }
}
