<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model" nsURI="model" nsPrefix="model">
  <eClassifiers xsi:type="ecore:EDataType" name="Time" instanceClassName="java.sql.Time"/>
  <eClassifiers xsi:type="ecore:EClass" name="A">
    <eStructuralFeatures xsi:type="ecore:EReference" name="b" lowerBound="1" upperBound="-1" eType="#//B" eOpposite="#//B/a"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="B">
    <eStructuralFeatures xsi:type="ecore:EReference" name="c" lowerBound="0" upperBound="-1" eType="#//C"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="a" lowerBound="1" upperBound="5" eType="#//A" eOpposite="#//A/b"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="C">
  </eClassifiers>
</ecore:EPackage>