/*
 * generated by Xtext
 */
package cruise.umple.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class UmpleUiModule extends cruise.umple.ui.AbstractUmpleUiModule {
	public UmpleUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
