#!/bin/csh -fb
if ! $?UMPLEROOT then
  setenv UMPLEROOT ~/umple
endif
echo Building Diagrams at $UMPLEROOT

cd $UMPLEROOT/cruise.umple/src

umple -g GvClassDiagram --override -c - --path $UMPLEROOT/dist/cruise.umple/reference DiagramMaster.ump
mv $UMPLEROOT/dist/cruise.umple/reference/DiagramMastercd.svg $UMPLEROOT/dist/cruise.umple/reference/Mastercd.svg
rm $UMPLEROOT/dist/cruise.umple/reference/DiagramMastercd.gv

umple -g GvClassDiagram --override -c - --path $UMPLEROOT/dist/cruise.umple/reference DiagramCoreMaster.ump
rm $UMPLEROOT/dist/cruise.umple/reference/DiagramCoreMastercd.gv

umple -g GvClassDiagram --override -c - --path $UMPLEROOT/dist/cruise.umple/reference DiagramStateMaster.ump
rm $UMPLEROOT/dist/cruise.umple/reference/DiagramStateMastercd.gv

echo To open user diagram master open $UMPLEROOT/dist/cruise.umple/reference/umple-compiler-classDiagram.shtml
