#!/bin/csh -fb
if ! $?UMPLEROOT then
  setenv UMPLEROOT ~/umple
endif
cd $UMPLEROOT/build
echo Doing final UmpleOnline setup in $UMPLEROOT
echo Copying jars from dist director to the umpleonline scripts directory
echo Do this after qfbumple when resting umpleonline
ant -DshouldPackageUmpleOnline=true -Dmyenv=local -f build.umple.xml packageUmpleonline
cd $UMPLEROOT/umpleonline/scripts
echo restarting the umpleonline server
$UMPLEROOT/dev-tools/quitserver
echo restarting the docker server for code execution
$UMPLEROOT/dev-tools/startexecdocker
echo restarting the lsp docker server
$UMPLEROOT/dev-tools/startlspdocker
echo rebuilding the codemirror6 tech
cd $UMPLEROOT/umpleonline/scripts/codemirror6
npm start
echo rebuilding the openai sdk bundle
cd $UMPLEROOT/umpleonline/scripts/openai-sdk
npm start

