#!/bin/csh -fb
if ! $?UMPLEROOT then
  setenv UMPLEROOT ~/umple
endif
cd $UMPLEROOT/build
echo Doing quick build of Umple and its jars at $UMPLEROOT ( umpleSelf compile packageJars )
echo This should take 12-25 seconds. Do not interrupt
echo You should always have done 'git pull' or fetch and merge before running this and have resolved conflicts
ant -Dmyenv=local -f build.umple.xml umpleSelf compile packageJars 
