#!/bin/csh -fb
if ! $?UMPLEROOT then
  setenv UMPLEROOT ~/umple
endif
cd $UMPLEROOT/build
echo "Doing quick build of Umple and its jars at $UMPLEROOT ( codegen umpleParser rtcpp umpleSelf compile packageJars )"
echo This should take 12-25 seconds. Do not interrupt
echo You should always have done 'git pull' before running this and have resolved conflicts
set logfile="/tmp/umplebuildlog$$.txt"
ant -Dmyenv=local -f build.umple.xml codegen umpleParser rtcpp umpleSelf compile packageJars | tee $logfile
grep -qi failed $logfile
set failedstatus=$status
grep -qi error $logfile
if ($status == 0 || $failedstatus == 0) then
  echo "************************"
  echo The word FAILED or ERROR was found in the above. Build was NOT SUCCESSFUL.
  echo Build log is at $logfile
else
  rm $logfile
endif
