#!/bin/csh -fb
if ! $?UMPLEROOT then
  setenv UMPLEROOT ~/umple
endif
echo Quitting any umpleonline server that is running in $UMPLEROOT/umpleonline/scripts
cd $UMPLEROOT/umpleonline/scripts
php UmpleServerTest.php server -quit 
