#!/bin/csh -fb
if ! $?UMPLEROOT then
  setenv UMPLEROOT ~/umple
endif
echo Starting background docker for code execution in $UMPLEROOT/UmpleCodeExecution
cd $UMPLEROOT/UmpleCodeExecution
if (`uname -n` == 'cruise') then
  sudo ./setup.sh bg
else
  ./setup.sh bg
endif

echo Starting background docker for umple collaboration in $UMPLEROOT/UmpleCollabServer
cd $UMPLEROOT/UmpleCollabServer
if (`uname -n` == 'cruise') then
  sudo ./setup.sh bg
else
  ./setup.sh bg
endif