#!/bin/csh -fb
if ! $?UMPLEROOT then
  setenv UMPLEROOT ~/umple
endif
echo Starting background docker for code execution in $UMPLEROOT/UmpleCodeExecution
cd $UMPLEROOT/UmpleCodeExecution
if (`uname -n` == cruise)
  sudo ./setup.sh
else
  ./setup.sh
endif