require 'rake'
require 'rake/testtask'

task :default => [:testbed]

desc "Run basic tests"
Rake::TestTask.new("testbed") do |t|
  t.test_files = FileList['test/attributes/*_test.rb','test/associations/*_test.rb']
  t.verbose = true
  t.warning = true
end
