%The main TXL file. Translates the java generated by Umple to basic javascript

include "JavaScript.Grm"

%Comments are kept, since javascript uses the same comments as java
#pragma -comment

%--------------------%
%     Top level      %
%--------------------%
%Main function translates every class. Package and import statements are not needed in javascript
%Note that the TXL currently makes the assumption that 1 file = 1 class
function main
    replace [program]
    Jcomment1 [repeat comment_NL]
     _ [repeat package_statement]
    Jcomment2 [repeat comment_NL]
     _ [repeat import_statement]
    Jcomment3 [repeat comment_NL]
     classes [repeat class_declaration]
    by
    Jcomment1
    Jcomment2
    Jcomment3
    classes
        [replaceConcreteClasses]
end function

%--------------------%
%     Classes        %
%--------------------%

%Rule to translate concrete classes
rule replaceConcreteClasses
    replace $ [concrete_class_declaration]
        _ [opt acess_modifier] _ [opt 'abstract] 'class className [id] inheritances [repeat inheritance_list] '{ classBody [class_body_decl] '}
    export className
    construct translatedBody [class_body_decl]
        classBody [replaceClassBody]
    construct requireStatement [opt require_statement]
        _ [createRequire each inheritances]
    construct extendsGroup [opt extends_group]
        _ [createExtends each inheritances]
    by
        requireStatement 'class className extendsGroup '{ translatedBody '} 'module.'exports '= className ';
end rule

%CommonJS: the superclass is required from the file generated next to this one
function createRequire inheritance [inheritance_list]
    replace [opt require_statement]
        _ [opt require_statement]
    deconstruct inheritance
        'extends superClass [id]
    construct fileName [stringlit]
        _ [+ "./"] [quote superClass] [+ ".js"]
    by
        'const superClass '= 'require( fileName ');
end function

function createExtends inheritance [inheritance_list]
    replace [opt extends_group]
        _ [opt extends_group]
    deconstruct inheritance
        'extends superClass [id]
    by
        'extends superClass
end function

%Func contains logic to translate class bodies
%Member variable names and method names are exported, to be used when translating statements
function replaceClassBody
    replace [class_body_decl]
        body [class_body_decl]
    deconstruct body
        elements [repeat class_body_element]
    construct declarations [repeat member_variable_declaration]
        _ [^ elements]
    export memberVariables [repeat id]
        _ [addMemberVariable each declarations]
    construct classMethods [repeat method_declaration]
        _ [^ elements]
    export classMethodNames [repeat id]
        _ [extractConcreteMethodName each classMethods]
    export staticMethodNames [repeat id]
        _ [addStaticMethod each classMethods]
    by
        elements [removeMemberVariableDeclarations] [removeToString] [replaceConstructor] [replaceMethods]
end function

%If arg is a member variable declaration, add its name to results
function addMemberVariable MemberVariable [member_variable_declaration]
    replace [repeat id]
        SequenceSoFar [repeat id]
    deconstruct MemberVariable
        _[opt acess_modifier] _[opt transient] _[opt final] _[opt volatile]  _ [nested_identifier] memberName [id] _[opt member_variable_assignment] ';
    by
        SequenceSoFar [. memberName]
end function

%Adds concrete method name to repeat
function extractConcreteMethodName method [method_declaration]
    replace [repeat id]
        result [repeat id]
    deconstruct method
        _[opt decorator] _[acess_modifier] _[opt static] _[nested_identifier] methodName [id] '( _[list method_parameter] ') _[opt throws] '{ _[method_content] '}
    by
        result [. methodName]
end function

%If arg is a static method declaration, add its name to results
function addStaticMethod method [method_declaration]
    replace [repeat id]
        SequenceSoFar [repeat id]
    deconstruct method
        _[opt decorator] _[acess_modifier] 'static _[nested_identifier] methodName [id] '( _[list method_parameter] ') _[opt throws] '{ _[method_content] '}
    by
        SequenceSoFar [. methodName]
end function

%Javascript does not have member variable declarations like Java does
%This function removes all member variable declarations
function removeMemberVariableDeclarations
    replace [repeat class_body_element]
        elems [repeat class_body_element]
    construct empty [repeat class_body_element]
        _
    by
        empty [addIfNotMemberDecleration each elems]
end function

%If the argument is not a member variable, add it to results
function addIfNotMemberDecleration elem [class_body_element]
    replace [repeat class_body_element]
        keepers [repeat class_body_element]
    construct declerations [repeat member_variable_declaration]
        _ [^ elem]
    construct declerationSize [number]
        _ [length declerations]
    where
        declerationSize [= 0]
    by
        keepers [. elem]
end function

%The generated toString uses java specific code. It is not part of basic javascript generation
function removeToString
    replace [repeat class_body_element]
        elems [repeat class_body_element]
    construct empty [repeat class_body_element]
        _
    by
        empty [addIfNotToString each elems]
end function

%If the argument is not the toString method, add it to results
function addIfNotToString elem [class_body_element]
    replace [repeat class_body_element]
        keepers [repeat class_body_element]
    construct toStringMethods [repeat id]
        _ [extractToString elem]
    construct toStringSize [number]
        _ [length toStringMethods]
    where
        toStringSize [= 0]
    by
        keepers [. elem]
end function

function extractToString elem [class_body_element]
    replace [repeat id]
        result [repeat id]
    deconstruct elem
        _[opt decorator] _[acess_modifier] _[opt static] _[nested_identifier] 'toString '( ') _[opt throws] '{ _[method_content] '}
    by
        result [. 'toString]
end function

%--------------------%
%     Methods        %
%--------------------%

%Rule to translate the constructor
rule replaceConstructor
    replace [constructor]
        _ [acess_modifier] _ [id] '( params [list method_parameter] ') _ [opt throws] '{ statements [repeat statement] '}
    construct newParams [list method_parameter]
        _ [translateParam each params]
    by
        'constructor '( newParams ') '{ statements [replaceStatements newParams] '}
end rule

%Rule to translate concrete methods
rule replaceMethods
    replace [concrete_method_declaration]
        _ [opt decorator] _ [acess_modifier] isStatic [opt static] _ [nested_identifier] methodName [id] '( params [list method_parameter] ') _ [opt throws] '{ content [method_content] '}
    deconstruct content
        statements [repeat statement]
    construct newParams [list method_parameter]
        _ [translateParam each params]
    by
        isStatic methodName '( newParams ') '{ statements [replaceStatements newParams] '}
end rule

%Javascript parameters have no types
function translateParam param [method_parameter]
    replace [list method_parameter]
        SequenceSoFar [list method_parameter]
    deconstruct param
        _ [nested_identifier] paramName [id]
    construct newParam [method_parameter]
        paramName
    by
        SequenceSoFar [, newParam]
end function

%--------------------%
%     Statements     %
%--------------------%

%Translates the statements of a constructor or method
%Parameters and local variables are not member variables, even if they have the same name
function replaceStatements params [list method_parameter]
    replace [repeat statement]
        statements [repeat statement]
    construct paramNames [repeat id]
        _ [^ params]
    construct declarations [repeat double_value]
        _ [^ statements]
    construct localVars [repeat id]
        paramNames [addLocalVariable each declarations]
    construct intVars [repeat id]
        _ [addIntVariable each declarations]
    import memberVariables [repeat id]
    import classMethodNames [repeat id]
    import staticMethodNames [repeat id]
    by
        statements
            [replaceDecleration]
            [replaceMemberVariableNames memberVariables localVars]
            [replaceThisMemberVariableNames memberVariables]
            [addThisToOwnMethodCalls classMethodNames staticMethodNames]
            [addClassToStaticMethodCalls staticMethodNames]
            [replaceNewList]
            [replaceNewListCopy]
            [replaceForInLoop]
            [replaceUnmodifiableList]
            [replaceListGet]
            [replaceListSize]
            [replaceListContains]
            [replaceListAdd]
            [replaceListAddAtIndex]
            [replaceListRemoveAtIndex intVars]
            [replaceListRemove]
            [replaceListClear]
            [replaceListIsEmpty]
            [replaceEquals]
            [replaceOwnEquals]
end function

%If arg is a local variable declaration, add its name to results
function addLocalVariable declaration [double_value]
    replace [repeat id]
        SequenceSoFar [repeat id]
    deconstruct declaration
        _ [value] declared [value]
    deconstruct * [id] declared
        localName [id]
    by
        SequenceSoFar [. localName]
end function

%If arg is a local int variable declaration, add its name to results
%Java lists remove an element at an index when given an int
function addIntVariable declaration [double_value]
    replace [repeat id]
        SequenceSoFar [repeat id]
    deconstruct declaration
        'int declared [value]
    deconstruct * [id] declared
        localName [id]
    by
        SequenceSoFar [. localName]
end function

%Javascript variables are declared with let instead of a type
rule replaceDecleration
    replace $ [double_value]
        _ [value] declared [value]
    by
        'let declared
end rule

%Member variables are accessed through this, with an underscore like the python generator
rule replaceMemberVariableNames memberVariables [repeat id] localVars [repeat id]
    replace [nested_identifier]
        name [id] accesses [repeat attribute_access]
    where
        memberVariables [contains name]
    where not
        localVars [contains name]
    construct newName [id]
        _ [+ "_"] [+ name]
    construct newAccesses [repeat attribute_access]
        '. newName
    by
        'this newAccesses [. accesses]
end rule

%Member variables already accessed through this (ex: this.school = null)
rule replaceThisMemberVariableNames memberVariables [repeat id]
    replace [nested_identifier]
        'this '. name [id] accesses [repeat attribute_access]
    where
        memberVariables [contains name]
    construct newName [id]
        _ [+ "_"] [+ name]
    by
        'this '. newName accesses
end rule

%Calls to methods of the same class are done through this
rule addThisToOwnMethodCalls classMethodNames [repeat id] staticMethodNames [repeat id]
    replace [nested_identifier]
        name [id] args [func_call_parentheses] accesses [repeat attribute_access]
    where
        classMethodNames [contains name]
    where not
        staticMethodNames [contains name]
    construct calls [repeat attribute_access]
        '. name args
    by
        'this calls [. accesses]
end rule

%Static methods are called through the class
rule addClassToStaticMethodCalls staticMethodNames [repeat id]
    replace [nested_identifier]
        name [id] args [func_call_parentheses] accesses [repeat attribute_access]
    where
        staticMethodNames [contains name]
    import className [id]
    construct calls [repeat attribute_access]
        '. name args
    by
        className calls [. accesses]
end rule

rule contains Object [id]
    match [id]
        Object
end rule

%--------------------%
%       Lists        %
%--------------------%
%Associations use java lists. Javascript uses arrays instead

rule replaceNewList
    replace [base_value]
        'new 'ArrayList '< _ [list id] '> '( ')
    by
        '[ ']
end rule

%A list created from another list is a copy of it
rule replaceNewListCopy
    replace [base_value]
        'new 'ArrayList '< _ [list id] '> '( source [value] ')
    deconstruct source
        name [nestable_value] accesses [repeat attribute_access]
    construct slice [repeat attribute_access]
        '. 'slice '( ')
    by
        name accesses [. slice]
end rule

%Javascript loops through the elements of a list with of
rule replaceForInLoop
    replace [for_in_loop]
        'for( declaration [double_value] ': elements [value] ') '{ statements [repeat statement] '}
    by
        'for '( declaration 'of elements ') '{ statements '}
end rule

rule replaceUnmodifiableList
    replace [nested_identifier]
        'Collections '. 'unmodifiableList '( listValue [value] ')
    deconstruct listValue
        name [nestable_value] accesses [repeat attribute_access]
    construct slice [repeat attribute_access]
        '. 'slice '( ')
    by
        name accesses [. slice]
end rule

rule replaceListGet
    replace [repeat attribute_access]
        '. name [id] extensions [repeat nestable_extension] '. 'get '( index [value] ') accesses [repeat attribute_access]
    construct element [repeat nestable_extension]
        '[ index ']
    by
        '. name extensions [. element] accesses
end rule

rule replaceListSize
    replace [attribute_access]
        '. 'size '( ')
    by
        '. 'length
end rule

rule replaceListContains
    replace [attribute_access]
        '. 'contains '( element [value] ')
    by
        '. 'includes '( element ')
end rule

rule replaceListAdd
    replace [attribute_access]
        '. 'add '( element [value] ')
    by
        '. 'push '( element ')
end rule

rule replaceListAddAtIndex
    replace [attribute_access]
        '. 'add '( index [value] ', element [value] ')
    by
        '. 'splice '( index ', '0 ', element ')
end rule

rule replaceListRemoveAtIndex intVars [repeat id]
    replace [nested_identifier]
        'this '. name [id] '. 'remove '( index [value] ')
    deconstruct index
        indexName [id]
    where
        intVars [contains indexName]
    by
        'this '. name '. 'splice '( index ', '1 ')
end rule

%Like java, nothing is removed when the element is not in the list
rule replaceListRemove
    replace [statement]
        'this '. name [id] '. 'remove '( element [value] ') ';
    by
        'if '( 'this '. name '. 'includes '( element ') ') '{
            'this '. name '. 'splice '( 'this '. name '. 'indexOf '( element ') ', '1 ') ';
        '}
end rule

rule replaceListClear
    replace [attribute_access]
        '. 'clear '( ')
    by
        '. 'splice '( '0 ')
end rule

rule replaceListIsEmpty
    replace [base_value]
        'this '. name [id] '. 'isEmpty '( ')
    by
        '( 'this '. name '. 'length '== '0 ')
end rule

%Generated classes do not redefine equals, so it compares references
rule replaceEquals
    replace [base_value]
        object [nestable_value] '. 'equals '( other [value] ')
    by
        '( object '== other ')
end rule

%The inherited equals of the class itself (ex: equals(existingDesk))
rule replaceOwnEquals
    replace [base_value]
        'equals '( other [value] ')
    by
        '( 'this '== other ')
end rule
