<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="docs" nsURI="cruise.umple.docs" nsPrefix="docs">
  <eClassifiers xsi:type="ecore:EDataType" name="Time" instanceClassName="java.sql.Time"/>
  <eClassifiers xsi:type="ecore:EClass" name="Documenter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inputPath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="outputPath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="messages" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parser" lowerBound="0" upperBound="1" eType="#//ContentParser" eOpposite="#//ContentParser/documenter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Content">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shouldIncludeReference" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="syntax" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="examples" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="group" lowerBound="1" upperBound="1" eType="#//Group" eOpposite="#//Group/contents"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Group">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contents" lowerBound="0" upperBound="-1" eType="#//Content" eOpposite="#//Content/group"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contentParser" lowerBound="1" upperBound="1" eType="#//ContentParser" eOpposite="#//ContentParser/groups"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContentParser" eSuperTypes="#//Parser">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="init" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>`
    <eStructuralFeatures xsi:type="ecore:EReference" name="groups" lowerBound="0" upperBound="-1" eType="#//Group" eOpposite="#//Group/contentParser"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="documenter" lowerBound="1" upperBound="1" eType="#//Documenter" eOpposite="#//Documenter/parser"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Template">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="htmlTemplate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exampleTemplate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="syntaxTemplate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="navigationHeaderTemplate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="navigationItemTemplate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="navigationItemTemplateNoAnchor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GeneratorHelper">
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CodeGenerator" interface="true" abstract="true">
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EcoreGenerator" eSuperTypes="#//CodeGenerator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" eType="#//UmpleModel"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="output" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PapyrusGenerator" eSuperTypes="#//CodeGenerator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" eType="#//UmpleModel"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="output" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="smName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diagramID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="smID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="regionID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XmiGenerator" eSuperTypes="#//CodeGenerator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" eType="#//UmpleModel"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="output" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TextUmlGenerator" eSuperTypes="#//CodeGenerator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" eType="#//UmpleModel"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="output" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GvStateDiagramGenerator" eSuperTypes="#//CodeGenerator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" eType="#//UmpleModel"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="output" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GvClassDiagramGenerator" eSuperTypes="#//CodeGenerator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" eType="#//UmpleModel"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="output" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimulateGenerator" eSuperTypes="#//CodeGenerator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" eType="#//UmpleModel"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="output" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YumlGenerator" eSuperTypes="#//CodeGenerator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" eType="#//UmpleModel"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="outputPath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JsonGenerator" eSuperTypes="#//CodeGenerator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" eType="#//UmpleModel"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="output" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JavaGenerator" eSuperTypes="#//CodeGenerator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" eType="#//UmpleModel"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="output" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CppGenerator" eSuperTypes="#//CodeGenerator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" eType="#//UmpleModel"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="output" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="callHeader" eType="#//boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="callLttng" eType="#//boolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="boolean"/>
  <eClassifiers xsi:type="ecore:EClass" name="PhpGenerator" eSuperTypes="#//CodeGenerator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" eType="#//UmpleModel"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="output" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RubyGenerator" eSuperTypes="#//CodeGenerator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" eType="#//UmpleModel"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="output" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SqlGenerator" eSuperTypes="#//CodeGenerator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" eType="#//UmpleModel"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="output" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SDLGenerator" eSuperTypes="#//CodeGenerator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" eType="#//UmpleModel"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="output" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JsonParser" eSuperTypes="#//Parser">
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Json">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="composites" eType="#//Json" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arrays" eType="#//Json" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Couple">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="open" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="close" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="couple" lowerBound="0" upperBound="1" eType="#//Couple" eOpposite="#//Couple/ignores"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ignores" lowerBound="0" upperBound="-1" eType="#//Couple" eOpposite="#//Couple/couple"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parsers" lowerBound="0" upperBound="-1" eType="#//Parser" eOpposite="#//Parser/couples"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParseResult">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="wasSuccess" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasWarning" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="_acceptsError" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="position" lowerBound="0" upperBound="1" eType="#//Position" eOpposite="#//Position/parseResults"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="errorMessages" lowerBound="0" upperBound="-1" eType="#//ErrorMessage" eOpposite="#//ErrorMessage/parseResults"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ErrorMessage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameters" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="errorType" lowerBound="1" upperBound="1" eType="#//ErrorType" eOpposite="#//ErrorType/errorMessages"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="position" lowerBound="1" upperBound="1" eType="#//Position" eOpposite="#//Position/errorMessages"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parseResults" lowerBound="0" upperBound="-1" eType="#//ParseResult" eOpposite="#//ParseResult/errorMessages"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ErrorType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="errorCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>`
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="severity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>`
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="errorFormat" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="errorUrl" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="errorMessages" lowerBound="0" upperBound="-1" eType="#//ErrorMessage" eOpposite="#//ErrorMessage/errorType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="errorTypeSingleton" lowerBound="1" upperBound="1" eType="#//ErrorTypeSingleton" eOpposite="#//ErrorTypeSingleton/errorTypes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="umpleInternalParser" lowerBound="1" upperBound="1" eType="#//UmpleInternalParser" eOpposite="#//UmpleInternalParser/messagesToExpect"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="umpleInternalParser" lowerBound="1" upperBound="1" eType="#//UmpleInternalParser" eOpposite="#//UmpleInternalParser/warningsToIgnore"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ErrorTypeSingleton">
    <eStructuralFeatures xsi:type="ecore:EReference" name="errorTypes" lowerBound="0" upperBound="-1" eType="#//ErrorType" eOpposite="#//ErrorType/errorTypeSingleton"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Token">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentToken" lowerBound="0" upperBound="1" eType="#//Token" eOpposite="#//Token/subTokens"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subTokens" lowerBound="0" upperBound="-1" eType="#//Token" eOpposite="#//Token/parentToken"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="position" lowerBound="0" upperBound="1" eType="#//Position" eOpposite="#//Position/tokens"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="umpleClassifiers" lowerBound="0" upperBound="-1" eType="#//UmpleClassifier" eOpposite="#//UmpleClassifier/extendsToken"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Position">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filename" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lineNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>`
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="characterOffset" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>`
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="offset" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>`
    <eStructuralFeatures xsi:type="ecore:EReference" name="parseResults" lowerBound="0" upperBound="-1" eType="#//ParseResult" eOpposite="#//ParseResult/position"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="errorMessages" lowerBound="0" upperBound="-1" eType="#//ErrorMessage" eOpposite="#//ErrorMessage/position"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tokens" lowerBound="0" upperBound="-1" eType="#//Token" eOpposite="#//Token/position"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rulePartValues" lowerBound="0" upperBound="-1" eType="#//RulePartValue" eOpposite="#//RulePartValue/position"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="umpleElement" lowerBound="1" upperBound="1" eType="#//UmpleElement" eOpposite="#//UmpleElement/positions"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shouldHide" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="definitions" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parsers" lowerBound="0" upperBound="-1" eType="#//Parser" eOpposite="#//Parser/rules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RulePartValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="position" lowerBound="0" upperBound="1" eType="#//Position" eOpposite="#//Position/rulePartValues"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RulePart">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nextIdentifiers" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximumPartsFound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>`
    <eStructuralFeatures xsi:type="ecore:EReference" name="ruleInstances" lowerBound="0" upperBound="-1" eType="#//RuleInstance" eOpposite="#//RuleInstance/ruleParts"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//Type" />
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Type">
    <eLiterals name="Static" value="0"/>
    <eLiterals name="Variable" value="1"/>
    <eLiterals name="Rule" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parser">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filename" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="grammarRules" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parseResult" eType="#//ParseResult"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="_curParsePo" eType="#//Position"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rootToken" eType="#//Token"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rules" lowerBound="0" upperBound="-1" eType="#//Rule" eOpposite="#//Rule/parsers"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="couples" lowerBound="0" upperBound="-1" eType="#//Couple" eOpposite="#//Couple/parsers"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ruleInstances" lowerBound="0" upperBound="-1" eType="#//RuleInstance" eOpposite="#//RuleInstance/parser"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RuleInstance">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stopAts" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="updateIndex" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>`
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rulePartsIndex" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>`
    <eStructuralFeatures xsi:type="ecore:EReference" name="ruleParts" lowerBound="0" upperBound="-1" eType="#//RulePart" eOpposite="#//RulePart/ruleInstances"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parser" lowerBound="1" upperBound="1" eType="#//Parser" eOpposite="#//Parser/ruleInstances"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StateMachine">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="umpleClass" lowerBound="0" upperBound="1" eType="#//UmpleClass" eOpposite="#//UmpleClass/stateMachines"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentState" lowerBound="0" upperBound="1" eType="#//State" eOpposite="#//State/nestedStateMachines"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="states" lowerBound="0" upperBound="-1" eType="#//State" eOpposite="#//State/stateMachine"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="umpleModel" lowerBound="1" upperBound="1" eType="#//UmpleModel" eOpposite="#//UmpleModel/stateMachineDefinitions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="traceRecords" lowerBound="0" upperBound="-1" eType="#//TraceRecord" eOpposite="#//TraceRecord/stateMachines"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stateMachineTraceItems" lowerBound="0" upperBound="-1" eType="#//StateMachine_TraceItem" eOpposite="#//StateMachine_TraceItem/stateMachine"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="State">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isConcurrent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isStartState" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isInternal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isHistoryState" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDeepHistoryState" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="finalState" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activity" lowerBound="0" upperBound="1" eType="#//Activity" eOpposite="#//Activity/state"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" lowerBound="0" upperBound="-1" eType="#//Action" eOpposite="#//Action/state"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stateMachine" lowerBound="1" upperBound="1" eType="#//StateMachine" eOpposite="#//StateMachine/states"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nestedStateMachines" lowerBound="0" upperBound="-1" eType="#//StateMachine" eOpposite="#//StateMachine/parentState"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transitions" lowerBound="0" upperBound="-1" eType="#//Transition" eOpposite="#//Transition/fromState"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nextTransition" lowerBound="0" upperBound="-1" eType="#//Transition" eOpposite="#//Transition/nextState"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Activity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="position" eType="#//Position"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="activityCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="codeblock" eType="#//CodeBlock"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="onCompletionEvent" lowerBound="0" upperBound="1" eType="#//Event" eOpposite="#//Event/activities"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="state" lowerBound="1" upperBound="1" eType="#//State" eOpposite="#//State/activity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isInternal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="autoTransition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" lowerBound="0" upperBound="1" eType="#//Event" eOpposite="#//Event/transitions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fromState" lowerBound="1" upperBound="1" eType="#//State" eOpposite="#//State/transitions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nextState" lowerBound="1" upperBound="1" eType="#//State" eOpposite="#//State/nextTransition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="guard" lowerBound="0" upperBound="1" eType="#//Guard" eOpposite="#//Guard/transitions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" lowerBound="0" upperBound="1" eType="#//Action" eOpposite="#//Action/transition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stateMachineTraceItems" lowerBound="0" upperBound="-1" eType="#//StateMachine_TraceItem" eOpposite="#//StateMachine_TraceItem/transition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="actionType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="position" eType="#//Position"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="actionCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isInternal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="codeblock" eType="#//CodeBlock"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="state" lowerBound="0" upperBound="1" eType="#//State" eOpposite="#//State/actions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transition" lowerBound="0" upperBound="1" eType="#//Transition" eOpposite="#//Transition/action"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Event">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="arg" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isTimer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="autoTransition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timerInSecond" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isInternal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activities" lowerBound="0" upperBound="-1" eType="#//Activity" eOpposite="#//Activity/onCompletionEvent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transitions" lowerBound="0" upperBound="-1" eType="#//Transition" eOpposite="#//Transition/event"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Guard">
    <eStructuralFeatures xsi:type="ecore:EReference" name="position" eType="#//Position"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="codeblock" eType="#//CodeBlock"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transitions" lowerBound="0" upperBound="-1" eType="#//Transition" eOpposite="#//Transition/guard"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TextParser">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="_currentName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="_lastCharacterIndex" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>`
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="_currentCharacterIndex" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>`
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="_maxCharacterIndex" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>`
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="indexToReplacementOffsetMap" eType="#//Hashtable%3CInteger%2CInteger%3E"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="_text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="_filename" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Hashtable&lt;Integer,Integer>" instanceClassName="java.util.Hashtable"/>
  <eClassifiers xsi:type="ecore:EClass" name="UmletGenerator" eSuperTypes="#//CodeGenerator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filename" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" eType="#//UmpleModel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classElements" lowerBound="0" upperBound="-1" eType="#//UmletElement" eOpposite="#//UmletElement/umletGenerators"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="associationElements" lowerBound="0" upperBound="-1" eType="#//UmletElement" eOpposite="#//UmletElement/umletGenerators"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UmletDiagram">
    <eStructuralFeatures xsi:type="ecore:EReference" name="umletElements" lowerBound="0" upperBound="-1" eType="#//UmletElement" eOpposite="#//UmletElement/umletDiagrams"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UmletElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="panelAttribute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="additionalAttribute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="coordinate" lowerBound="1" upperBound="1" eType="#//Coordinate" eOpposite="#//Coordinate/umletElements"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="umletGenerators" lowerBound="0" upperBound="-1" eType="#//UmletGenerator" eOpposite="#//UmletGenerator/classElements"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="umletGenerators" lowerBound="0" upperBound="-1" eType="#//UmletGenerator" eOpposite="#//UmletGenerator/associationElements"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="umletDiagrams" lowerBound="0" upperBound="-1" eType="#//UmletDiagram" eOpposite="#//UmletDiagram/umletElements"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UmpleModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="umpleFile" eType="#//UmpleFile"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultPackage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generates" eType="#//GenerateTarget" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shouldGenerate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="glossary" eType="#//Glossary"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultNamespace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="debugMode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lastResult" eType="#//ParseResult"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="generatedCode" eType="#//Map%3CString%2CString%3E"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="levelOffset" eType="#//Coordinate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initialOffset" eType="#//Coordinate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classSize" eType="#//Coordinate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxYLevel" eType="#//int"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="offsetFromEdge" eType="#//Coordinate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reflexiveSegmentLength" eType="#//int"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="traceType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="versionNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="associations" lowerBound="0" upperBound="-1" eType="#//Association" eOpposite="#//Association/umpleModel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="umpleClasses" lowerBound="0" upperBound="-1" eType="#//UmpleClass" eOpposite="#//UmpleClass/umpleModel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stateMachineDefinitions" lowerBound="0" upperBound="-1" eType="#//StateMachine" eOpposite="#//StateMachine/umpleModel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="umpleInterfaces" lowerBound="0" upperBound="-1" eType="#//UmpleInterface" eOpposite="#//UmpleInterface/umpleModel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generatedClasses" lowerBound="0" upperBound="-1" eType="#//GeneratedClass" eOpposite="#//GeneratedClass/model"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Map&lt;String,String>"/>
  <eClassifiers xsi:type="ecore:EDataType" name="int"/>
  <eClassifiers xsi:type="ecore:EClass" name="UmpleElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="namespaces" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="packageName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="extraCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isInternal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="coordinate" eType="#//Coordinate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="displayColor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="positions" lowerBound="0" upperBound="-1" eType="#//Position" eOpposite="#//Position/umpleElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Method">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="position" eType="#//Position"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isImplemented" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="methodParameters" lowerBound="0" upperBound="-1" eType="#//MethodParameter" eOpposite="#//MethodParameter/method"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="methodBody" lowerBound="0" upperBound="1" eType="#//MethodBody" eOpposite="#//MethodBody/method"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="comments" lowerBound="0" upperBound="-1" eType="#//Comment" eOpposite="#//Comment/method"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="umpleClassifier" lowerBound="1" upperBound="1" eType="#//UmpleClassifier" eOpposite="#//UmpleClassifier/methods"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Modifier">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="names" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MethodBody">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="extraCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="codeblock" eType="#//CodeBlock"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="method" lowerBound="1" upperBound="1" eType="#//Method" eOpposite="#//Method/methodBody"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constant">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="umpleClassifier" lowerBound="1" upperBound="1" eType="#//UmpleClassifier" eOpposite="#//UmpleClassifier/constants"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UniqueIdentifier" eSuperTypes="#//UmpleVariable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="umpleClass" lowerBound="1" upperBound="1" eType="#//UmpleClass" eOpposite="#//UmpleClass/uniqueIdentifier"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MethodParameter" eSuperTypes="#//UmpleVariable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAutounique" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isList" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDerived" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isLazy" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="method" lowerBound="1" upperBound="1" eType="#//Method" eOpposite="#//Method/methodParameters"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type">
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrimitiveType" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReferenceType" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EReference" name="umpleClass" lowerBound="0" upperBound="1" eType="#//UmpleClass" eOpposite="#//UmpleClass/referenceTypes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="umpleInterface" lowerBound="0" upperBound="1" eType="#//UmpleInterface" eOpposite="#//UmpleInterface/referenceTypes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstraintVariable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="constrainedVariable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAttribute" eType="#//boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAssociation" eType="#//boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="index" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>`
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isPrimitive" eType="#//boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isNumeric" eType="#//boolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expressions" eType="#//ConstraintVariable" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="umpleClass" lowerBound="1" upperBound="1" eType="#//UmpleClass" eOpposite="#//UmpleClass/constraints"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CodeBlock">
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CodeInjection">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="snippet" eType="#//CodeBlock"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="position" eType="#//Position"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isInternal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="umpleClass" lowerBound="1" upperBound="1" eType="#//UmpleClass" eOpposite="#//UmpleClass/codeInjections"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="umpleClass" lowerBound="1" upperBound="1" eType="#//UmpleClass" eOpposite="#//UmpleClass/codeInjections"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Key">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDefault" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="members" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UmpleClassifier" eSuperTypes="#//UmpleElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="methods" lowerBound="0" upperBound="-1" eType="#//Method" eOpposite="#//Method/umpleClassifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="depends" lowerBound="0" upperBound="-1" eType="#//Depend" eOpposite="#//Depend/umpleClassifiers"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constants" lowerBound="0" upperBound="-1" eType="#//Constant" eOpposite="#//Constant/umpleClassifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extendsToken" lowerBound="0" upperBound="1" eType="#//Token" eOpposite="#//Token/umpleClassifiers"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UmpleInterface" eSuperTypes="#//UmpleClassifier">
    <eStructuralFeatures xsi:type="ecore:EReference" name="umpleInterfaces" lowerBound="0" upperBound="-1" eType="#//UmpleInterface" eOpposite="#//UmpleInterface/extendsInterface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extendsInterface" lowerBound="0" upperBound="-1" eType="#//UmpleInterface" eOpposite="#//UmpleInterface/umpleInterfaces"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="umpleModel" lowerBound="1" upperBound="1" eType="#//UmpleModel" eOpposite="#//UmpleModel/umpleInterfaces"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenceTypes" lowerBound="0" upperBound="-1" eType="#//ReferenceType" eOpposite="#//ReferenceType/umpleInterface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="umpleClasses" lowerBound="0" upperBound="-1" eType="#//UmpleClass" eOpposite="#//UmpleClass/parentInterface"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UmpleClass" eSuperTypes="#//UmpleClassifier">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAbstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isSingleton" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="associations" eType="#//Association" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="key" eType="#//Key"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="iAmImmutable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ancestorIsImmutable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceModel" eType="#//UmpleModel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="codeInjections" lowerBound="0" upperBound="-1" eType="#//CodeInjection" eOpposite="#//CodeInjection/umpleClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" lowerBound="0" upperBound="-1" eType="#//Constraint" eOpposite="#//Constraint/umpleClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subclasses" lowerBound="0" upperBound="-1" eType="#//UmpleClass" eOpposite="#//UmpleClass/extendsClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extendsClass" lowerBound="0" upperBound="1" eType="#//UmpleClass" eOpposite="#//UmpleClass/subclasses"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentInterface" lowerBound="0" upperBound="-1" eType="#//UmpleInterface" eOpposite="#//UmpleInterface/umpleClasses"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="uniqueIdentifier" lowerBound="0" upperBound="1" eType="#//UniqueIdentifier" eOpposite="#//UniqueIdentifier/umpleClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" lowerBound="0" upperBound="-1" eType="#//Attribute" eOpposite="#//Attribute/umpleClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="associationVariables" lowerBound="0" upperBound="-1" eType="#//AssociationVariable" eOpposite="#//AssociationVariable/umpleClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="comments" lowerBound="0" upperBound="-1" eType="#//Comment" eOpposite="#//Comment/umpleClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="traceDirectives" lowerBound="0" upperBound="-1" eType="#//TraceDirective" eOpposite="#//TraceDirective/umpleClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="traceCases" lowerBound="0" upperBound="-1" eType="#//TraceCase" eOpposite="#//TraceCase/umpleClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stateMachines" lowerBound="0" upperBound="-1" eType="#//StateMachine" eOpposite="#//StateMachine/umpleClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="umpleModel" lowerBound="1" upperBound="1" eType="#//UmpleModel" eOpposite="#//UmpleModel/umpleClasses"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenceTypes" lowerBound="0" upperBound="-1" eType="#//ReferenceType" eOpposite="#//ReferenceType/umpleClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="codeInjections" lowerBound="0" upperBound="-1" eType="#//CodeInjection" eOpposite="#//CodeInjection/umpleClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generatedClass" lowerBound="0" upperBound="1" eType="#//GeneratedClass" eOpposite="#//GeneratedClass/uClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Depend">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isInternal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="umpleClassifiers" lowerBound="0" upperBound="-1" eType="#//UmpleClassifier" eOpposite="#//UmpleClassifier/depends"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AssociationClass" eSuperTypes="#//UmpleClass">
    <eStructuralFeatures xsi:type="ecore:EReference" name="associatedTo" lowerBound="0" upperBound="2" eType="#//Association" eOpposite="#//Association/associationClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UmpleVariable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute" eSuperTypes="#//UmpleVariable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAutounique" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isList" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDerived" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="codeblock" eType="#//CodeBlock"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isLazy" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="comments" lowerBound="0" upperBound="-1" eType="#//Comment" eOpposite="#//Comment/attribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="umpleClass" lowerBound="1" upperBound="1" eType="#//UmpleClass" eOpposite="#//UmpleClass/attributes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="traceRecords" lowerBound="0" upperBound="-1" eType="#//TraceRecord" eOpposite="#//TraceRecord/attributes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributeTraceItems" lowerBound="0" upperBound="-1" eType="#//Attribute_TraceItem" eOpposite="#//Attribute_TraceItem/attributes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Association">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isLeftNavigable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isRightNavigable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="positions" eType="#//Coordinate" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tokenPosition" eType="#//Position"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="immutable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ends" lowerBound="2" upperBound="2" eType="#//AssociationEnd" eOpposite="#//AssociationEnd/association"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="umpleModel" lowerBound="1" upperBound="1" eType="#//UmpleModel" eOpposite="#//UmpleModel/associations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="associationClass" lowerBound="1" upperBound="1" eType="#//AssociationClass" eOpposite="#//AssociationClass/associatedTo"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AssociationEnd">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="roleName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="className" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="referenceToClassName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="multiplicity" eType="#//Multiplicity"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDefaultRoleName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="priority" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="association" lowerBound="0" upperBound="1" eType="#//Association" eOpposite="#//Association/ends"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AssociationVariable" eSuperTypes="#//UmpleVariable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="multiplicity" eType="#//Multiplicity"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isNavigable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="priority" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="comments" lowerBound="0" upperBound="-1" eType="#//Comment" eOpposite="#//Comment/associationVariable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="umpleClass" lowerBound="0" upperBound="1" eType="#//UmpleClass" eOpposite="#//UmpleClass/associationVariables"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="traceDirective" lowerBound="0" upperBound="1" eType="#//TraceDirective" eOpposite="#//TraceDirective/associationVariable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Multiplicity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minimum" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximum" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GeneratedElement">
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GeneratedClass" eSuperTypes="#//GeneratedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" lowerBound="1" upperBound="1" eType="#//UmpleModel" eOpposite="#//UmpleModel/generatedClasses"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="uClass" lowerBound="1" upperBound="1" eType="#//UmpleClass" eOpposite="#//UmpleClass/generatedClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generatedClass" lowerBound="0" upperBound="1" eType="#//GeneratedClass" eOpposite="#//GeneratedClass/parentClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentClass" lowerBound="0" upperBound="1" eType="#//GeneratedClass" eOpposite="#//GeneratedClass/generatedClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Point">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>`
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>`
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Coordinate">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>`
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>`
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>`
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>`
    <eStructuralFeatures xsi:type="ecore:EReference" name="umletElements" lowerBound="0" upperBound="-1" eType="#//UmletElement" eOpposite="#//UmletElement/coordinate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="#//Status" />
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Status">
    <eLiterals name="Explicit" value="0"/>
    <eLiterals name="Undefined" value="1"/>
    <eLiterals name="Defaulted" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Comment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="method" lowerBound="1" upperBound="1" eType="#//Method" eOpposite="#//Method/comments"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="umpleClass" lowerBound="1" upperBound="1" eType="#//UmpleClass" eOpposite="#//UmpleClass/comments"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" lowerBound="1" upperBound="1" eType="#//Attribute" eOpposite="#//Attribute/comments"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="associationVariables" lowerBound="0" upperBound="-1" eType="#//AssociationVariable" eOpposite="#//AssociationVariable/umpleClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenerateTarget">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="language" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="override" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="overrideAll" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TraceCondition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="conditionType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="preCondition" eType="#//boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="postCondition" eType="#//boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lh" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rhs" lowerBound="1" upperBound="1" eType="#//ConditionRhs" eOpposite="#//ConditionRhs/traceCondition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="traceDirective" lowerBound="1" upperBound="1" eType="#//TraceDirective" eOpposite="#//TraceDirective/condition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConditionRhs">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rh" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comparisonOperator" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="traceCondition" lowerBound="0" upperBound="1" eType="#//TraceCondition" eOpposite="#//TraceCondition/rhs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TraceRecord">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="recordOnly" eType="#//boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="record" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" lowerBound="0" upperBound="-1" eType="#//Attribute" eOpposite="#//Attribute/traceRecords"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stateMachines" lowerBound="0" upperBound="-1" eType="#//StateMachine" eOpposite="#//StateMachine/traceRecords"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="traceDirective" lowerBound="1" upperBound="1" eType="#//TraceDirective" eOpposite="#//TraceDirective/traceRecord"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MethodTraceEntity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="entry" eType="#//boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exit" eType="#//boolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="traceDirectives" lowerBound="0" upperBound="-1" eType="#//TraceDirective" eOpposite="#//TraceDirective/methodTraceEntities"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TraceDirective">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>`
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributeTraceItems" lowerBound="0" upperBound="-1" eType="#//Attribute_TraceItem" eOpposite="#//Attribute_TraceItem/traceDirective"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stateMachineTraceItems" lowerBound="0" upperBound="-1" eType="#//StateMachine_TraceItem" eOpposite="#//StateMachine_TraceItem/traceDirectives"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="methodTraceEntities" lowerBound="0" upperBound="-1" eType="#//MethodTraceEntity" eOpposite="#//MethodTraceEntity/traceDirectives"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="associationVariable" lowerBound="0" upperBound="1" eType="#//AssociationVariable" eOpposite="#//AssociationVariable/traceDirective"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="0" upperBound="-1" eType="#//TraceCondition" eOpposite="#//TraceCondition/traceDirective"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="traceRecord" lowerBound="0" upperBound="1" eType="#//TraceRecord" eOpposite="#//TraceRecord/traceDirective"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="traceCases" lowerBound="0" upperBound="-1" eType="#//TraceCase" eOpposite="#//TraceCase/traceDirectives"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="umpleClass" lowerBound="0" upperBound="1" eType="#//UmpleClass" eOpposite="#//UmpleClass/traceDirectives"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute_TraceItem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="traceSet" eType="#//boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="traceGet" eType="#//boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="forClause" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>`
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="periodClause" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duringClause" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="executeClause" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" lowerBound="0" upperBound="-1" eType="#//Attribute" eOpposite="#//Attribute/attributeTraceItems"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="traceDirective" lowerBound="1" upperBound="1" eType="#//TraceDirective" eOpposite="#//TraceDirective/attributeTraceItems"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StateMachine_TraceItem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="entry" eType="#//boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exit" eType="#//boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="traceStateMachineFlag" eType="#//boolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stateMachine" lowerBound="0" upperBound="1" eType="#//StateMachine" eOpposite="#//StateMachine/stateMachineTraceItems"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transition" lowerBound="0" upperBound="1" eType="#//Transition" eOpposite="#//Transition/stateMachineTraceItems"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="traceDirectives" lowerBound="0" upperBound="-1" eType="#//TraceDirective" eOpposite="#//TraceDirective/stateMachineTraceItems"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TraceCase">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="traceDirectives" lowerBound="0" upperBound="-1" eType="#//TraceDirective" eOpposite="#//TraceDirective/traceCases"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="umpleClass" lowerBound="0" upperBound="1" eType="#//UmpleClass" eOpposite="#//UmpleClass/traceCases"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RuntimeException">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="str" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parent" eType="#//Exception"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Exception" instanceClassName="java.lang.Exception"/>
  <eClassifiers xsi:type="ecore:EClass" name="UmpleCompilerException" eSuperTypes="#//RuntimeException">
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SemanticException">
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UmpleFile">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="file" eType="#//File"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileContent" eType="#//StringBuilder"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="File" instanceClassName="java.io.File"/>
  <eClassifiers xsi:type="ecore:EDataType" name="StringBuilder" instanceClassName="java.lang.StringBuilder"/>
  <eClassifiers xsi:type="ecore:EClass" name="UmpleParserFactory">
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UmpleInternalParser" eSuperTypes="#//Parser">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="currentPackageName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="packageNameUsed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="outputUmpleSource" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" eType="#//UmpleModel"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unparsedUmpleFiles" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parsedUmpleFiles" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shouldProcessAgain" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shouldProcessClassAgain" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="unlinkedAssociationVariables" eType="#//AssociationVariable" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="unlinkedAssociations" eType="#//Association" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="positionToClassNameReference" eType="#//Map%3CPosition%2CString%3E"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unlinkedExtend" eType="#//Map%3CUmpleClassifier%2CList%3CString%3E%3E"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unlinkedExtendsToken" eType="#//Map%3CUmpleClassifier%2CList%3CToken%3E%3E"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unlinkedExtendsTokensInterface" eType="#//Map%3CUmpleClassifier%2CList%3CToken%3E%3E"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unlinkedInterfaceExtend" eType="#//Map%3CUmpleClassifier%2CList%3CString%3E%3E"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastComment" eType="#//List%3CComment%3E"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="placeholderStateMachine" eType="#//StateMachine"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stateMachineNameToToken" eType="#//Map%3CString%2CToken%3E"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="possiblyUnknownState" eType="#//Map%3CState%2CList%3CToken%3E%3E"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="messagesToExpect" lowerBound="0" upperBound="-1" eType="#//ErrorType" eOpposite="#//ErrorType/umpleInternalParser"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="warningsToIgnore" lowerBound="0" upperBound="-1" eType="#//ErrorType" eOpposite="#//ErrorType/umpleInternalParser"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="strictness" eType="#//Strictness" />
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Map&lt;Position,String>"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Map&lt;UmpleClassifier,List&lt;String>>"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Map&lt;UmpleClassifier,List&lt;Token>>"/>
  <eClassifiers xsi:type="ecore:EDataType" name="List&lt;Comment>"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Map&lt;String,Token>"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Map&lt;State,List&lt;Token>>"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Strictness">
    <eLiterals name="none" value="0"/>
    <eLiterals name="modelOnly" value="1"/>
    <eLiterals name="noExtraCode" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pair">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UmpleParser" interface="true" abstract="true">
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UmpleXtextParser" eSuperTypes="#//UmpleParser">
    <eStructuralFeatures xsi:type="ecore:EReference" name="temp" eType="#//UmpleInternalParser"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SynchronizationAction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deltaCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="umpleCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UpdatePositioningAction" eSuperTypes="#//SynchronizationAction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="umpleParser" eType="#//UmpleParser"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="textParser" eType="#//TextParser"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="jsonParser" eType="#//JsonParser"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="json" eType="#//Json"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="addedPositions" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="UmpleParser" instanceClassName="cruise.umple.compiler.UmpleParser"/>
  <eClassifiers xsi:type="ecore:EClass" name="NewAction" eSuperTypes="#//SynchronizationAction">
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EditAction" eSuperTypes="#//SynchronizationAction">
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeleteAction" eSuperTypes="#//SynchronizationAction">
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NewAssociationAction" eSuperTypes="#//SynchronizationAction">
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EditAssociationAction" eSuperTypes="#//SynchronizationAction">
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeleteAssociationAction" eSuperTypes="#//SynchronizationAction">
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeleteGeneralizationAction" eSuperTypes="#//SynchronizationAction">
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NewGeneralizationAction" eSuperTypes="#//SynchronizationAction">
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VioletGenerator" eSuperTypes="#//CodeGenerator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filename" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" eType="#//UmpleModel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="violetClasses" lowerBound="0" upperBound="-1" eType="#//VioletClass" eOpposite="#//VioletClass/violetGenerators"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="violetAssociations" lowerBound="0" upperBound="-1" eType="#//VioletAssociation" eOpposite="#//VioletAssociation/violetGenerators"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VioletDiagram">
    <eStructuralFeatures xsi:type="ecore:EReference" name="violetClasses" lowerBound="0" upperBound="-1" eType="#//VioletClass" eOpposite="#//VioletClass/violetDiagram"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="violetAssociations" lowerBound="0" upperBound="-1" eType="#//VioletAssociation" eOpposite="#//VioletAssociation/violetDiagram"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VioletClass">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="violetClasses" lowerBound="0" upperBound="-1" eType="#//VioletClass" eOpposite="#//VioletClass/parentClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentClass" lowerBound="0" upperBound="1" eType="#//VioletClass" eOpposite="#//VioletClass/violetClasses"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="violetGenerators" lowerBound="0" upperBound="-1" eType="#//VioletGenerator" eOpposite="#//VioletGenerator/violetClasses"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="violetDiagram" lowerBound="1" upperBound="1" eType="#//VioletDiagram" eOpposite="#//VioletDiagram/violetClasses"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="violetAssociations" lowerBound="0" upperBound="-1" eType="#//VioletAssociation" eOpposite="#//VioletAssociation/violetClasses"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VioletAssociation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startLabel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endLabel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="violetClasses" lowerBound="1" upperBound="2" eType="#//VioletClass" eOpposite="#//VioletClass/violetAssociations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="violetGenerators" lowerBound="0" upperBound="-1" eType="#//VioletGenerator" eOpposite="#//VioletGenerator/violetAssociations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="violetDiagram" lowerBound="1" upperBound="1" eType="#//VioletDiagram" eOpposite="#//VioletDiagram/violetAssociations"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VmlSystem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="codeSnippets" lowerBound="0" upperBound="-1" eType="#//CodeSnippet" eOpposite="#//CodeSnippet/vmlSystem"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="concerns" lowerBound="0" upperBound="-1" eType="#//Concern" eOpposite="#//Concern/vmlSystem"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vmlParser" lowerBound="0" upperBound="1" eType="#//VmlParser" eOpposite="#//VmlParser/system"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Concern">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variationPoints" lowerBound="0" upperBound="-1" eType="#//VariationPoint" eOpposite="#//VariationPoint/concern"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vmlSystem" lowerBound="0" upperBound="1" eType="#//VmlSystem" eOpposite="#//VmlSystem/concerns"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariationPoint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="codeSnippet" lowerBound="0" upperBound="1" eType="#//CodeSnippet" eOpposite="#//CodeSnippet/variationPoint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variants" lowerBound="0" upperBound="-1" eType="#//Variant" eOpposite="#//Variant/variationPoint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variationPoints" lowerBound="0" upperBound="-1" eType="#//VariationPoint" eOpposite="#//VariationPoint/requires"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requires" lowerBound="0" upperBound="-1" eType="#//VariationPoint" eOpposite="#//VariationPoint/variationPoints"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="concern" lowerBound="0" upperBound="1" eType="#//Concern" eOpposite="#//Concern/variationPoints"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//Kind" />
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Kind">
    <eLiterals name="Optional" value="0"/>
    <eLiterals name="Alternative" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variant">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="codeSnippet" lowerBound="0" upperBound="1" eType="#//CodeSnippet" eOpposite="#//CodeSnippet/variant"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variationPoint" lowerBound="0" upperBound="1" eType="#//VariationPoint" eOpposite="#//VariationPoint/variants"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CodeSnippet">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vmlSystem" lowerBound="0" upperBound="1" eType="#//VmlSystem" eOpposite="#//VmlSystem/codeSnippets"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variationPoint" lowerBound="0" upperBound="1" eType="#//VariationPoint" eOpposite="#//VariationPoint/codeSnippet"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variant" lowerBound="0" upperBound="1" eType="#//Variant" eOpposite="#//Variant/codeSnippet"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VmlParser" eSuperTypes="#//Parser">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="variationPointToRequiresListMap" eType="#//Map%3CVariationPoint%2CList%3CString%3E%3E"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="invokedVariation" eType="#//List%3CVariationPoint%3E"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="system" lowerBound="0" upperBound="1" eType="#//VmlSystem" eOpposite="#//VmlSystem/vmlParser"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Map&lt;VariationPoint,List&lt;String>>"/>
  <eClassifiers xsi:type="ecore:EDataType" name="List&lt;VariationPoint>"/>
  <eClassifiers xsi:type="ecore:EClass" name="UmpleConsoleMain">
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UmpleRunMain">
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PlaygroundMain">
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StatsMain">
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MetricsCollector">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="logs" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TriState">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isSet" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Language">
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Input">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stream" eType="#//InputStream"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reader" eType="#//BufferedReader"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="InputStream" instanceClassName="java.io.InputStream"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BufferedReader" instanceClassName="java.io.BufferedReader"/>
  <eClassifiers xsi:type="ecore:EClass" name="FileManager">
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActionResponse">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="default_success_message_id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="successMessage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="errors" eType="#//ErrorItem" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ErrorItem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parts" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringFormatter">
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SampleFileWriter">
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeleteLanguage">
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Word">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="singular" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="plural" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Glossary">
    <eStructuralFeatures xsi:type="ecore:EReference" name="words" eType="#//Word" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExceptionDumper">
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Object">
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassLoader">
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Command">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="histories" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="messages" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attributes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="currentObject" eType="#//Object"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="loader" eType="#//ClassLoader"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Builder">
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DynamicClassPathLoader">
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DocumenterMain">
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TraceItem">
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VmlConsole">
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CodeCompiler">
  </eClassifiers>
</ecore:EPackage>
