
/*
 * generated by Xtext
 */
 
package cruise.umple.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 *@generated
 */
public class UmpleExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return cruise.umple.ui.internal.UmpleActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return cruise.umple.ui.internal.UmpleActivator.getInstance().getInjector("cruise.umple.Umple");
	}
	
}
