/*
* generated by Xtext
*/
package cruise.umple.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import cruise.umple.services.UmpleGrammarAccess;

public class UmpleParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private UmpleGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected cruise.umple.parser.antlr.internal.InternalUmpleParser createParser(XtextTokenStream stream) {
		return new cruise.umple.parser.antlr.internal.InternalUmpleParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "UmpleModel";
	}
	
	public UmpleGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(UmpleGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
