/*
* generated by Xtext
*/
package cruise.umple.ui.contentassist;

import cruise.umple.ui.contentassist.AbstractUmpleProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class UmpleProposalProvider extends AbstractUmpleProposalProvider {

}
