/*
* generated by Xtext
*/
package cruise.umple.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class UmpleOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
