/*
* generated by Xtext
*/
package cruise.umple.ui.outline;

import org.eclipse.xtext.ui.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class UmpleTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
