/*
* generated by Xtext
*/
package cruise.umple;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class UmpleUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return cruise.umple.ui.internal.UmpleActivator.getInstance().getInjector("cruise.umple.Umple");
	}
	
}
